import { randomWords } from '@v8187/rs-mock';
import { randomItem } from '@v8187/rs-utils';

import { CaseModel } from '../models/case.model';
import { bool, phoneNo, recentDate, pName, gender, country, state, city, } from './utils';
import { UserModel } from '../models/user.model';
import { caseTypes, relationTypes } from '../configs/enum-constants';

// Add Default Cases data
const common = {};

const actualCasesData = [{
    contactNo: '9988125734',
    referredOn: '05/02/2017',
    approvedOn: '05/02/2017',
    description: 'fees of Babli\'s Son Master Om',
    title: 'Monthly school fee for single mother\'s Son',
    caseType: 'education',
    name: 'Master Om',
    contactRelation: 'mother',
    contactPerson: 'Babli',
    gender: 'm',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9988125734',
    referredOn: '05/02/2017',
    approvedOn: '05/02/2017',
    title: 'Monthly ration support for single mother with kids',
    description: 'Monthly ration support for single mother with kids',
    caseType: 'ration',
    name: 'Babli',
    contactRelation: 'self',
    contactPerson: 'Babli',
    gender: 'f',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9988125734',
    referredOn: '05/02/2017',
    approvedOn: '05/02/2017',
    description: 'fees of Babli\'s daughter Shikha',
    title: 'Monthly school fee for single mother\'s daughter',
    caseType: 'education',
    name: 'Shikha',
    contactRelation: 'mother',
    contactPerson: 'Babli',
    gender: 'f',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9988125734',
    referredOn: '05/02/2017',
    approvedOn: '05/02/2017',
    description: 'other school charges of Babli\'s Son Master Om',
    title: 'Pay school charges (other than fee) of Babli\'s Son',
    caseType: 'education',
    name: 'Master Om',
    contactRelation: 'mother',
    contactPerson: 'Babli',
    gender: 'm',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9988125734',
    referredOn: '05/02/2017',
    approvedOn: '05/02/2017',
    description: 'Exams fees of Babli\'s Son Master Om',
    title: 'Pay Exam fee of Babli\'s Son',
    caseType: 'education',
    name: 'Master Om',
    contactRelation: 'mother',
    contactPerson: 'Babli',
    gender: 'm',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '7837046167',
    referredOn: '05/02/2017',
    approvedOn: '05/02/2017',
    description: 'Medicine of Ms. Sukhwant Kaur',
    title: 'Need Medicines for Ms. Sukhwant Kaur',
    caseType: 'medical',
    name: 'Sukhwant Kaur',
    contactRelation: 'self',
    contactPerson: 'Sukhwant Kaur',
    gender: 'f',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '8556873885',
    referredOn: '05/02/2017',
    approvedOn: '05/02/2017',
    description: 'Ration of Ustad ji\'s Wife Ms. Santosh',
    title: 'Need monthly ration for Ustad ji\'s wife Ms. Santosh',
    caseType: 'ration',
    name: 'Santosh Kumari',
    contactRelation: 'husband',
    contactPerson: 'Ustad ji',
    gender: 'f',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '8556873885',
    referredOn: '05/02/2017',
    approvedOn: '05/02/2017',
    description: 'electricity bill (partially)for Ms. Santosh Kumari wife of Ustad ji',
    title: 'Need to pay partial electricity bill',
    caseType: 'commodity',
    name: 'Santosh Kumari',
    contactRelation: 'husband',
    contactPerson: 'Ustad ji',
    gender: 'f',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9356165775',
    referredOn: '05/02/2017',
    approvedOn: '05/02/2017',
    description: 'ration for Mr. Rajinder Jain father of Ms. Chaina(Kidney patient)',
    // title: 'Monthly ration support for Mr. Rajinder Jain father of Ms. Chaina(Kidney patient)',
    title: 'Monthly ration support for Kidney patient\'s father',
    caseType: 'ration',
    name: 'Rajinder Jain',
    contactRelation: 'daughter',
    contactPerson: 'Chaina',
    gender: 'm',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '8054503726',
    referredOn: '05/02/2017',
    approvedOn: '05/02/2017',
    description: 'Manjit Singh\'s ration',
    title: 'Monthly ration support for Manjit Singh',
    caseType: 'ration',
    name: 'Manjit Singh',
    contactRelation: 'self',
    contactPerson: 'Manjit Singh',
    gender: 'm',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
},/*  {
    contactNo: '9803800801',
    referredOn: '07/02/2017',
    approvedOn: '07/02/2017',
    title: 'No Title',
    caseType: 'ration',
    name: 'Arvinder bir Singh',
    contactRelation: 'self',
    contactPerson: 'Arvinder bir Singh',
    description: 'एक बच्ची सिद्धक जो तीसरी कक्षा में पढ़ती थी फीस ना देने के कारण उसे कक्षा में नहीं बैठने दिया जा रहा था लेकिन पिछले महा जनवरी में हमारे कुछ सदस्यों ने उसकी फीस का कुछ हिस्सा देकर उसे दोबारा कक्षा में बिठाने में सफलता प्राप्त की। सिद्धक के पिताजी अरविंदर बीर सिंह पुत्र सरदार इंद्रपाल सिंह रेजिडेंस ऑफ न्यू कृष्णा नगर तरनतारन रोड अमृतसर के निवासी है जिनका मोबाइल नंबर 9803800801 है वह स्कूलों में आई कार्ड बनाने का काम करते हैं सीजनल काम होने के कारण वह बच्ची की फीस कई महीनों से नहीं भर पा रहे थे हमारे कुछ सदस्यों ने 3500 रुपए की राशि से उनकी मदद की एक सदस्य ने 1500 रुपए दिया दूसरे ने 1000 तीसरे ने 500 और चौथे ने भी 500 ऐसा करते हुए बच्ची की फीस भर कर उसे दोबारा कक्षा में बिठाने में हमारे सदस्य सफल हुए ऐसा करने के लिए हम उन सभी चार सदस्यों का तहे दिल से धन्यवाद करते हैं यह संदेश उन चार सदस्य और आप सभी की जानकारी के लिए है। धंयवाद',
    gender: 'm',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, */ {
    contactNo: '09817457597',
    referredOn: '09/02/2017',
    approvedOn: '09/02/2017',
    description: 'medicine of Mr. Yog Raj H/O Ms. Seema Devi (Epilepsy patient)',
    title: 'Buy medicines for Mr. Yog Raj (Epilepsy patient)',
    caseType: 'ration',
    name: 'Yog Raj',
    contactRelation: 'wife',
    contactPerson: 'Seema Devi',
    gender: 'm',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9888401807',
    referredOn: '09/02/2017',
    approvedOn: '09/02/2017',
    // description: 'Cash given to Kaka Swami (an ex grossery shop keeper, patient of hernia, prostate, diabetes)',
    description: 'Kaka swami.(an ex grossery shop keeper, patient of hernia, prostate, diabetes). n his sister.(who needs hip replacement) (both in their late 70\'s, unmarried, old n non_working) residents of gali hansali wali, chk lakshmansar, Asr, mobile no 9888401807,are running through financial crisis. \'Lets help\' offered a financial aid of Rs.1000 per month whereas kaka swami accepted only Rs.200.!!!!!! Per month and said\"jyada bojh ni pana chaunda main\"!!!!. LATER ON HE ACCEPTED 500 PER MONTH.',
    title: 'Financial help to old single person',
    caseType: 'financial',
    name: 'Kaka Swami',
    contactRelation: 'self',
    contactPerson: 'Kaka Swami',
    gender: 'm',
    age: 70,
    address: 'Gali Hansali Wali, Chowk Lakshmansar',
    isClosed: true,
    closedOn: '09/02/2017',
    closingReason: 'Kaka Swami ji expired',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9888401807',
    referredOn: '09/02/2017',
    approvedOn: '09/02/2017',
    title: 'Financial and medical help to old lady (sister of Late. Kaka Swami)',
    caseType: 'medical',
    name: 'Veena',
    contactRelation: 'self',
    contactPerson: 'Veena',
    description: 'आदरणीय सदस्यों, हमें आपके साथ यह शेयर करते हुए दुख हो रहा है की काका स्वामी जी का कुछ महीने पहले देहांत हो गया है जैसे कि आप लोग जानते हैं,आप लोग उन्हें प्रति महीना ₹500 की सहायता करते थे क्योंकि अब उनका देहांत हो गया है उनकी एक बहन जो कि 68 वर्षीय वीणा रेजिडेंस ऑफ गली हंसली वाली, चौक लक्ष्मणसर, अमृतसर मोबाइल नंबर9888401807) जिसकी हिप ज्वाइंट की प्रॉब्लम है और उनकी आंखों में भी प्रॉब्लम है हम चाहते हैं जो मदद हम पहले काका स्वामी को देते थे वह मदद अब हम उनकी बहन वीणा गंभीर को दे दे उनकी आंखों और हड्डियों की दवाई चलती है हम चाहते हैं कि उनको दवाइयों की सहायता कर दे कृपा हमें इजाजत दीजिए तो जो हम ऐसा कर सकें अन्यथा अपना सुझाव दीजिए धन्यवाद',
    gender: 'f',
    age: 68,
    address: 'Gali Hansali Wali, Chowk Lakshmansar',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9780014141',
    referredOn: '09/02/2017',
    approvedOn: '09/02/2017',
    description: 'dialysis of Mr. Harpreet Singh  [Kidneys patient]',
    title: 'Dialysis of Mr. Harpreet Singh  [Kidneys patient]',
    caseType: 'medical',
    name: 'Harpreet Singh',
    contactRelation: 'self',
    contactPerson: 'Harpreet Singh',
    gender: 'm',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9780014141',
    referredOn: '09/02/2017',
    approvedOn: '09/02/2017',
    title: 'Medicine support to Mr. Harpreet Singh',
    caseType: 'medical',
    name: 'Harpreet Singh',
    contactRelation: 'self',
    contactPerson: 'Harpreet Singh',
    gender: 'm',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '8988019080',
    referredOn: '09/02/2017',
    approvedOn: '09/02/2017',
    description: 'Ms. Sunita\'s ration',
    title: 'Help with monthly ration for Ms. Sunita',
    caseType: 'ration',
    name: 'Sunita',
    contactRelation: 'self',
    contactPerson: 'Sunita',
    gender: 'f',
    city: 'Palampur, Dharamshala',
    state: 'Himachal Pardesh',
    country: 'India',
}, {
    contactNo: '9418487962',
    referredOn: '09/02/2017',
    approvedOn: '09/02/2017',
    description: 'Ms. Meenu\'s ration',
    title: 'Help with monthly ration for Ms. Meenu',
    caseType: 'ration',
    name: 'Meenu',
    contactRelation: 'self',
    contactPerson: 'Meenu',
    gender: 'f',
    city: 'Palampur, Dharamshala',
    state: 'Himachal Pardesh',
    country: 'India',
}, {
    contactNo: '9988117605',
    referredOn: '09/02/2017',
    approvedOn: '09/02/2017',
    description: 'Saurabh Sharma (9988117605) Address.H.N o 807/8 Gali Tilyian Wali, Namak Mandi, Amritsar.(PB) Age.approx 26 year. Father Mother.Both expired. Brother.Also expired. Sister.married. House.Rented Rs.1500. Saurab has two braintumor and TB.operated for one braintumor but second braintumor medicine going on. INCOME.NIL. NO BODY IN THE FAMILY TO LOOK AFTER.friends, neighbour,other tenant and sister help him.',
    title: 'Financial support to braintumor and TB patient',
    caseType: 'financial',
    name: 'Saurabh Sharma',
    contactRelation: 'self',
    contactPerson: 'Saurabh Sharma',
    gender: 'm',
    age: 26,
    address: 'Address.H.N o 807/8 Gali Tilyian Wali, Namak Mandi',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '8194939616',
    referredOn: '09/02/2017',
    approvedOn: '09/02/2017',
    description: 'Mr. Shami kumar\'s account (father of Muskan) in State bank of India account no 32387716695 for school fees and tuition fees of Muskan',
    title: 'Support school and tuition fees of Muskan',
    caseType: 'education',
    name: 'Muskan',
    contactRelation: 'father',
    contactPerson: 'Shami Kumar',
    gender: 'm',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '7837047208',
    referredOn: '09/02/2017',
    approvedOn: '09/02/2017',
    description: 'for special child Master Gobind medicine',
    title: 'Help with medicines for special child',
    caseType: 'medical',
    name: 'Gobind',
    contactRelation: 'self',
    contactPerson: 'Gobind',
    gender: 'm',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '7837047208',
    referredOn: '09/02/2017',
    approvedOn: '09/02/2017',
    description: 'For special child Master Gobind admission fees',
    title: 'Admission fees for special child Master Gobind',
    caseType: 'education',
    name: 'Gobind',
    contactRelation: 'self',
    contactPerson: 'Gobind',
    gender: 'm',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9781957375',
    referredOn: '11/02/2017',
    approvedOn: '11/02/2017',
    title: 'Ration for Ms. Paramjeet kaur',
    caseType: 'ration',
    name: 'Paramjeet kaur',
    contactRelation: 'self',
    contactPerson: 'Paramjeet kaur',
    description: '(Widow with abnormal gril child)',
    gender: 'f',
    city: 'Jalandhar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9781957375',
    referredOn: '11/02/2017',
    approvedOn: '11/02/2017',
    title: 'LPG cylinder for Ms. Paramjeet kaur',
    caseType: 'ration',
    name: 'Paramjeet kaur',
    contactRelation: 'self',
    contactPerson: 'Paramjeet kaur',
    description: '(Widow with abnormal gril child)',
    gender: 'f',
    city: 'Jalandhar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9878821875',
    referredOn: '11/02/2017',
    approvedOn: '11/02/2017',
    title: 'One time help with admission fees (partial)',
    caseType: 'education',
    name: ' Chanchal Kumar',
    contactRelation: 'self',
    contactPerson: ' Chanchal Kumar',
    description: 'Name. Mr. Chanchal Kumar. S/O Shri Madan lal Sharam. Address.H No. 3890 D Adarsh Nagar. Amritsar Mobile No.9878821875 Mr. Chanchal works on one of our Member Mr. Mandeep Singh(9872764187) shop and earns Rs.6000 per month. Chanchal\'s father works on a sweet shop. Mother is house wife. Chanchal\'s Mother has very high blood pressure, breast nodules and overy tumour. Medicine of mother Approximately Rs.2000 per months. Mr. Chanchal has two children (Twins )one son and one daughter. Both studying at Nationa Public school, Adarsh Nagar. Amritsar, Admission fees for both the children is 18000. Mr. Mandeep(our member)and someone helped him to accumulate admission fees of wards but even then he has some shortage. Mr. Mandeep called us and asked to help Mr. Chanchal kumar with some amount in admission fees for once.(Approximately Rs.1500 to 2000) Case referred By our two member. Mr. Mandeep Singh (9872764187) Mr. Saurabh Sharma (9888552692) Please look into the matter and guide us.',
    gender: 'm',
    address: 'Address.H No. 3890 D Adarsh Nagar',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9876706517',
    referredOn: '02/15/2017',
    approvedOn: '02/15/2017',
    title: 'Need help in buying hearing aid for widow aged lady',
    caseType: 'medical',
    name: 'Aagya Kaur',
    age: 75,
    contactRelation: 'son',
    contactPerson: 'Name unknown',
    description: 'For hearing aid (Sunan wali machine) This case was referred by our member Mr. Harpreet Singh(Sonu) (9501029876) . Ms. Aagya Kaur (75 years old) w/o late S. Tirath Singh. Mob no. (9876706517 son\'s mobile no.)',
    gender: 'm',
    address: '42B Jamun Wali Gali. Tarn Taran Road',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '7508387342',
    referredOn: '02/22/2017',
    approvedOn: '02/22/2017',
    description: 'Neep help inpaying fee for 3 months',
    title: 'Mr. Rajinder Singh\'s daughter Isharpreet Kaur for three month\'s fees(December January and February 2016-17 )',
    caseType: 'education',
    name: 'Isharpreet Kaur',
    contactRelation: 'self',
    contactPerson: 'Rajinder Singh',
    gender: 'f',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9958235023',
    referredOn: '02/23/2017',
    approvedOn: '02/23/2017',
    description: 'Ration and medicine respectively for Ms. Jangir Kaur',
    title: 'Ration and medicine respectively for Ms. Jangir Kaur',
    caseType: 'ration',
    name: 'Jangir Kaur',
    contactRelation: 'self',
    contactPerson: 'Jangir Kaur',
    gender: 'f',
    city: 'New Delhi',
    state: 'New Delhi',
    country: 'India',
}, {
    contactNo: '9958235023',
    referredOn: '02/23/2017',
    approvedOn: '02/23/2017',
    description: 'Ration and medicine respectively for Ms. Jangir Kaur',
    title: 'Help with medicine for Ms. Jangir Kaur',
    caseType: 'medical',
    name: 'Jangir Kaur',
    contactRelation: 'self',
    contactPerson: 'Jangir Kaur',
    gender: 'f',
    city: 'New Delhi',
    state: 'New Delhi',
    country: 'India',
}, {
    contactNo: '9878664535',
    referredOn: '03/05/2017',
    approvedOn: '03/05/2017',
    title: 'Ration for Approximately Rs.800 to Rs.1000 for some months',
    caseType: 'ration',
    name: 'Sashi',
    contactRelation: 'self',
    contactPerson: 'Sashi',
    description: 'Below said case is referred by Our respected members 1. Mr. Rishi jain (9463590439) 2. Mr. Ashok jain (7837139022) 3. Mr. Kashish Mehra (9914032002) Name: Ms. Sashi (widow)W/O Late Shri Joginder Pal. Address: H.No 872/4, Katra Mohar Singh, Bazaar Kathatian. Amritsar (PB). Mobile no. 9878664535 Ms. Sashi has seven children. Six daughters and one son.(one daughter died at the age of eighteen because of TB) rest all are married. Her Son Bobby and his wife Poonam are little abnormal. Daughter-in-law has chest TB also. Sashi lives in the house of her husband\'s brother and works as sweeper in \"Babli School\"Wahian Wala Bazar Asr and earns approximately 2000 per month. Her son who is little mentally retarded also works in some shop to polish silver and earns approximately Rs.5000. Her grandson who is 11 years old and studies in 5th class is also little mentally abnormal. As her daugter in law has chest TB and she will have to take medicine for two more years along with good diet. So they need Ration from Let\'s Help for Approximately Rs.800 to Rs.1000 for some months. We request all the members to please guide us.',
    gender: 'f',
    address: 'H.No 872/4, Katra Mohar Singh, Bazaar Kathatian',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '8054922460',
    referredOn: '04/01/2017',
    approvedOn: '04/01/2017',
    title: 'Support with school fee of Naman Kanojia S/o Sh. Vikas kanojia',
    caseType: 'education',
    name: 'Naman Kanojia',
    contactRelation: 'father',
    contactPerson: 'Vikas Kanojia',
    description: 'Below said case is referred by our respected member Ms. Reenu Kappor. (9878604056) Name Mr. Vikas Kanojia. Address H.no 2184, Street no. 1, Gopal vihar, Majitha road, Amritsar.(PB) Mobile no. 8054922460 Mr. Vikas Kanojia is a washerman and earns Rs.6000 to 7000 appropriate per month. He has two sons,one 6 year and other few months old. His father irons the cloths. Wife used to work as sweeper in homes but because of child delivery now she is not able to work. They need one time help from Let\'s Help of Rs.2000 for their son\'s school fee who is student of UKG in Bright land school, Opp GNDH, Majitha Road, Asr. They have to pay approximately Rs 10000 to the school to get the result as well as admission in the new class which they are unable to pay. This Rs.10000 includes pending fee, admission fee, books and school uniform.',
    gender: 'm',
    address: 'Address H.no 2184, Street no. 1, Gopal vihar, Majitha road',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9781261886',
    referredOn: '04/10/2017',
    approvedOn: '04/10/2017',
    title: 'Needs help for getting the test (IVP) done',
    caseType: 'medical',
    name: 'Payal Malik',
    age: 12,
    contactRelation: 'mother',
    contactPerson: 'Simran',
    description: 'Below said case is referred by our respected member Mr. Ashish Goel (9888747409). Ms. Simran (age 30 years.widow) R/o Near Tarlok janj Ghar, Street Opp Pira Wali Gali, Gatu de School Wali Gali. Tran Taran Road, Amritsar. Mobile no. 9781261886. A widow whose husband died in 2016. Lives in a rented house for which she pays Rs 2000/-. She has only one daughter namely Payal Malik (12 years) who studies in Class 5th in Sri Guru Nanak Sr Secondary School, Ghee Mandi Amritsar. Simran works at a shop (IDH Market Shop No.45-46 Hargobind plastics Amritsar) and earns Rs 5000/-only. Unfortunately her daughter had stomach ache and she got her ultrasound done. Now the doctors have recommended a test (IVP) for which she has to pay approximately Rs.2000 to 2500. No relative is ready to give her a helping hand since her mother in law as well as her own mother, both are step mothers. In this scenario she needs help from \'LETS HELP\' for getting the test done. Your very valuable suggestions in this connection are solicited.',
    gender: 'f',
    address: 'R/o Near Tarlok janj Ghar, Street Opp Pira Wali Gali, Gatu de School Wali Gali. Tran Taran Road',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9780801515',
    referredOn: '05/21/2017',
    approvedOn: '05/21/2017',
    // title: '(65 years old) (Rs.5000 for hearing machine+400 hear testing charges total Rs.5400 ) Mob no. Pardeep ( 9780801515 )For hearing aid (Sunan wali machine)',
    title: 'Needs help with hearing machine and related tests',
    caseType: 'medical',
    name: 'Sindho',
    contactRelation: 'neighbours',
    contactPerson: 'Pradeep Kumar',
    description: '(Referred by our member Mr. Deepak Ratra.) Dear members A lady . Name Sindho Approximately age 65 years Main Gali Devi Wali H.No.764 Kailasho da Vehra, Jora Pipal, Near Namak Mandi, Amritsar. Mobile no. (Not available ) .was brought from Bombay as a house maid by another lady around 10 years ago. They obviously lived together for long ten years in the above said address which was a rented house. After getting services from Shindo for ten years, she expired. But now shindo is living in d same place since her husband has abondoned her from the last 10-15 yeaRs.She does not even know the whereabouts of her husband. Her two daughters too had expired. The landlord did not compel her to vacate the place. She earns only 3 to 5 hundred with tiffin service to different shops. Pradeep Kumar (9780801515) Gali Suniara wali Namak Mandi , the son of the lady who has expired helps Shindo a little bit and little bit neighbouRs.Shindo is in dire need of a hearing aid. Your suggestions in the same connection are solicited.',
    gender: 'f',
    age: 65,
    address: 'Main Gali Devi Wali H.No.764 Kailasho da Vehra, Jora Pipal, Near Namak Mandi',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9517840870',
    alternateNo1: '7508719697',
    referredOn: '07/21/2017',
    approvedOn: '07/21/2017',
    // title: 'BCA 1st year (1st installment) admission fee of Muskan d/o Mr. Shami Kumar',
    title: 'Help with admission fee of Muskan d/o Mr. Shami Kumar',
    caseType: 'education',
    name: 'Muskan',
    contactRelation: 'daughter',
    contactPerson: 'Shami Kumar',
    description: 'This is to inform all the members that Ms. Muskan (hailing from a family of five members with monthly income of about Rs.8000 , D/O Mr Shami Kumar, resident of H. No S 20/188, gali chawal wali, gali hansali wali, chowk Lakshmansar, Asr, Mob No. (9517840870) was offered help in form of her monthly fee Rs 1500. Now she has cleared her 12th class with 64% marks. \'Let\'s Help\' had got her admitted in Guru Teg Bahadur College for women for BCA , a three year degree course . The annual charges Rs 24010 (after the discount of Rs 2500) were to be paid in three instalments. \'Lets Help\' had paid the first instalment Rs.10930 and the rest two instalments will be paid as per the time period given by the above said college. Here we would also like to mention that the books, university fee and the other expenses will be done by the family itself. Thanx',
    gender: 'f',
    address: 'H. No S 20/188, gali chawal wali, gali hansali wali, chowk Lakshmansar',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9876526385',
    referredOn: '07/23/2017',
    approvedOn: '07/23/2017',
    title: 'Deposited in Ujjani Mehta (9876526385) SBI account no. 37046001167',
    caseType: 'ration',
    name: 'Ujjani Mehta',
    contactRelation: 'self',
    contactPerson: 'Ujjani Mehta',
    description: 'Dear members Mr. Amit Mehta (resident and owner of House No. 247, Ek roop Avenue, Majitha bypass, Majitha Road, Amritsar, (Mob. 9876526385) father of three daughters out of which two are twins, earns Rs.9000 only by working as besan (gram flour) salesman. His twins are 12 years and the third daughter is 5 yRs.One of the twins Ujjaini Mehta is deaf and dump but extremely beautiful child with a keen desire to study. A lot of money was spent on her treatment with no positive results. She cries and expresses her desire in her own unique style which obviously her parents understand. She was earlier studying in a special school where she has cleared her 2nd class but due to the money spent on the treatment of her grandfather who was a victim of bone cancer, the family is facing the monetary crisis. Unfortunately they couldn\'t save the old man inspite of all efforts. Since two other daughters are studying, Ujjaini also wants to study but the family can\'t afford the expenses. So the poor special child is sitting home vacant with the suppressed desire to study since last one year.She needs to be self sufficient economically too in future because of her condition. Let\'s Help wants to offer help to the family in the same context. Your very valuable permission is awaited. The case has been referred by our member Mr. Amit Kumar (9781052345). Thnx ',
    gender: 'f',
    address: 'House No. 247, Ek roop Avenue, Majitha bypass, Majitha Road',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9517821131',
    referredOn: '09/10/2017',
    approvedOn: '09/10/2017',
    title: 'Mr. Rajinder Singh\'s daughter Isharpreet Kaur for May June July and August month\'s fees',
    caseType: 'ration',
    name: 'Rajinder Singh',
    contactRelation: 'self',
    contactPerson: 'Rajinder Singh',
    gender: 'm',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9781423350',
    referredOn: '09/11/2017',
    approvedOn: '09/11/2017',
    title: 'Spent consultancy and lab tests for Master Jagnoor Singh S/O S. Prital Singh. 9781423350 At ranjit avenue, Amritsar',
    caseType: 'ration',
    name: 'Jagnoor Singh',
    contactRelation: 'self',
    contactPerson: 'Jagnoor Singh',
    description: 'Below said case referred by our respected member Mr. Ashok jain ji. Dear members Jagnoor Singh (2 years, S/O Sh.Pritpal Singh, owner of House No. 993, Dr. Hetram colony, Bombay wali gali, Narayan Garh, Chheharta, Mob No. 9781423350) can neither sit nor stand or walk by birth besides having fits at times. His father works at Narang hardware ( monthly salary ₹ 6000) whereas his mom applies laces (earns ₹ 500/1000). She had paralysis attack after pregnancy. His grandmom works as kitchen help in marriage functions. His grandfather has expired 18 years ago. His sister studies in LKG at Guru Nanak Mission Public School. Around ₹ 2 lac borrowed from the relatives was spent on the treatment of the child and his mom. \'Let\'s Help\' wants to offer help for doctor\'s fee, lab tests and medicine.Please allow us to proceed. Thanx',
    gender: 'm',
    age: 2,
    address: 'House No. 993, Dr. Hetram colony, Bombay wali gali, Narayan Garh, Chheharta',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9501355444',
    referredOn: '12/05/2017',
    approvedOn: '12/05/2017',
    title: 'spent for Mr. Santosh Kumar (9501355444) liver cancer patient',
    caseType: 'ration',
    name: 'Santosh Kumar',
    contactRelation: 'self',
    contactPerson: 'Santosh Kumar',
    description: 'Dear members, Sh. Santosh Kumar S/O Sh. Dalip Chand (Resident of H.no 123/11, Gali Mati Wali, Churasti Atari Chowk, Near Ucha Shivala, Amritsar (mobile no. 9501355444) joint property of him and his brother, has liver cancer. He lives with the family of his brother Sh Tarsam Singh. His son Sh. Ravinder Thakur too has mouth cancer. Both of them were taken to Mumbai for the treatment and around ₹ 6 lac has been spent on treatment with no positive results. Now he (Mr. Santosh) is admitted in Navpreet Hosp, Putlighar,Amritsar. Unfortunately his grandson too was medically unfit and he had some problem in his brain. He was only 3 and after 2 years treatment unluckily he couldn’t be saved and he left for heavenly abode on 03 Dec 2017. They spent 8 to 10 lac on grandson also. Sh. Ravinder used to work in Trilliam Mall, Amritsar as team leader and he would earn around ₹ 10000 there but now since he is not working bcoz of his illness, the family is now penniless and borrowing money from relatives. whereas Sh. Santosh and his son earn only ₹ . 5000 and Tarsam\'s son Shiv earn Rs.12000 which definitely is very insufficient for the family of 9. ‘Let’s Help’ wants to offer help of around ₹ 4000 to 5000 every month to this family which can be in form of medicines, hospital expenses or any other requested area. Your suggestions for the above said case are solicited. Thnx',
    gender: 'm',
    address: 'H.no 123/11, Gali Mati Wali, Churasti Atari Chowk, Near Ucha Shivala',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9592193431',
    referredOn: '12/25/2017',
    approvedOn: '12/25/2017',
    title: 'spent for the medicine (injections) for Mr. Vijay Kumar W/O Ms. Radhika.',
    caseType: 'ration',
    name: 'Vijay Kumar',
    contactRelation: 'self',
    contactPerson: 'Vijay Kumar',
    description: 'Dear members, BELOW SAID CASE IS REFERRED BY OUR RESPECTED MEMBER Mr. Gulshan Kumar ji. Vijay Kumar H/O Ms. Radhika (resident of Gali Gujran Wali, near Veenu Beauty Parlour, Chowk Baba Sahib, Amritsar,Mob: 9592193431 ), a liver failure patient, father of two daughters (3years and 3 months respectively ) used to work on someone’s shop on irregular basis where he would earn 5000 to 6000. He is a daily drinker. His parents have already expired. His wife alters old clothes and earns a few bucks. Her parents are not in state to render any help. They have been living in a rented house for the last 40 years and pay ₹ 200 for the same. Vijay has two sisters and one of them is widow and works as a helper in a hospital and doesn’t earn much to help her brother. Vijay was denied treatment in two hospitals over shortage of funds. Now he has been admitted in Guru Nanak Hospital, medical ward no. 6 bed no 20 Amritsar. ‘Let’s Help’ wants to render help to this family. Your valuable suggestions in the same context are solicited',
    gender: 'm',
    address: ' Gali Gujran Wali, near Veenu Beauty Parlour, Chowk Baba Sahib',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '8949531650',
    referredOn: '01/01/2018',
    approvedOn: '01/01/2018',
    title: 'spent for the medicines of Priyanka W/O Mr. Chit Kumar',
    caseType: 'ration',
    name: 'Priyanka',
    contactRelation: 'self',
    contactPerson: 'Priyanka',
    description: 'Below said case referred by our Respected member Ms. Kanika Mehra Mother of Mr. Sunny. Name. Ms. Priyanka(18 year old) Husband Name. Mr. Chit Kumar. Address. Ram Nagar Colony. Majitha Road, Amritsar. Mobile no. 8949531650 (Mother\'s mobile no.) Husband.Rickshaw puller. Father in law.off and on Rickshaw puller. House on rent.Rs.1500 Priyanka mother works in people home. All are from West Bengal Prinka Father went to West Bengal 6-7 months ago but did not come back. Priyanka delivered a child few days back and after delivery fits problem. (Perhaps.brain problem or epilepsy) Priyanka is admitted in Bajwa Hosp, Fatehgarh Churian Rd, Amritsar in ICU. They need help from let\'s help.',
    gender: 'f',
    address: 'Ram Nagar Colony. Majitha Road',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '8894830417',
    referredOn: '02/03/2018',
    approvedOn: '02/03/2018',
    title: 'spent for ration of Ms. Sumitra. (Chamba -HP)',
    caseType: 'ration',
    name: 'Sumitra',
    contactRelation: 'self',
    contactPerson: 'Sumitra',
    description: 'Below said case referred by our respected members Ms. Rekha Kalanoriya, Ms. Nisha Kumari, and Ms. Simmi (All from Himachal pradesh). Ms. Sumitra, w/o Late Sh. Man Singh. Age 40 yeaRs.Address: Village Binjori. P.O Salwan. Bazar Telka. Tehsil Saluni. Distt. Chamba.(H.P) Mobile no. 8894830417 Six years ago Sumitra\'s husband has met with an accident and expired.He was a private driver. Sumitra works in people home. She gets very nominal widow pension quarterly also. She has 3 daughters and two sons. The eldest daughter is married. Second daughter used to do maid work in people home and earn Rs.2000 monthly but now no work. The youngest one is studying in 8th standard but she is not in good health. Her treatment is going on. Elder son who is sixteen years old, doing the job of a labourer n earning approximately Rs.1000/- monthly. The younger son is studying in class 5th. Economic condition is so poor that sometime they have to take food from people. As they live in remote area so they get the work on and off. She has her own house. Relatives help off and on. She needs a helping hand from Let\'s Help in the form of ration. Please give your consent and guide us.',
    gender: 'f',
    age: 40,
    address: 'Village Binjori. P.O Salwan. Bazar Telka. Tehsil Saluni. Distt. Chamba.(H.P)',
    city: 'Chamba',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '6280223208',
    referredOn: '02/04/2018',
    approvedOn: '02/04/2018',
    title: 'spent for medical test and medicines for Ms. Arvinder Kaur',
    caseType: 'ration',
    name: 'Arvinder Kaur',
    contactRelation: 'self',
    contactPerson: 'Arvinder Kaur',
    description: 'Below said case referred by newly joined respected member Mr. Simran jeet Singh ji. MRs.Arvinder Kaur (around 50+) w/o S. Harjit Singh (resident of , ₹ 2000 monthly rented House No. 322, New Shaheed Udam Singh Nagar, Gali number 3, Amritsar). is admitted in a SGRD hospital at walla in the ward of Dr. Manjeet Singh Uppal, with a stomach problem and waiting for some monetary help for the MRI and medical tests which doctors there have recommended. Her problem has not yet been diagnosed. She had been suffering from stomach problem since last 6 months. She has been admitted three times in Shri Guru Ram Dass hospital near Shaheedan under Dr. Navjot Brar’s supervision. They had to take loan of more than ₹ 1 lac for the same. Her husband used to earn ₹ 4000-5000 per month with carpentry but now from last many years he is having some neuro related problem because of which he often falls unconscious with foaming at mouth, so not working these days. A lot of money with no improvement of his health is spent on him too. Her son Mr. Honey (22 yr) works in shop at Tej Nagar where copper jewellery is made. He earns only ₹ 2500 per month. Earlier she used to do some tiny tasks and would earn ₹ 2000-3000 but now that earning too is at halt. Her married daughter and parental relatives are not financially sound enough to help them. Mobile no. of Ms. Arvinder\'s son is 6280223208. Let’s help wants to render help to them. Your valuable suggestions are solicited for the same.',
    gender: 'f',
    age: 50,
    address: 'House No. 322, New Shaheed Udam Singh Nagar, Gali number 3',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '7508129724',
    referredOn: '02/21/2018',
    approvedOn: '02/21/2018',
    title: 'spent for school fees of Mr. Suraj Sharma (Cancer patient) children',
    caseType: 'ration',
    name: 'Suraj Sharma',
    contactRelation: 'self',
    contactPerson: 'Suraj Sharma',
    description: 'नीचे दिया गया केस हमारे आदरणीय सदस्य श्री सौरभ शर्मा जी द्वारा रेफर किया गया है। प्रिय सदस्यों, यह आज का केस एक कैंसर पेशेंट का है। सूरज शर्मा जो कि 32 साल का है (मोबाइल नंबर 7508129724) नमक मंडी, बड़ा मंदिर, तबेला जगतराम, अमृतसर में रहता है। वह एक छोटे से कमरे में रहते हैं जो कि मंदिर की और से मिला हुआ है यह कमरा पिछले 70 साल से उनके पास है और कोई किराया भी नहीं देना पड़ता। उसकी छाती मैं कैंसर है दो बार वहां से टुकड़ा निकालकर चेक किया गया है। उसका इलाज गुरु नानक हॉस्पिटल से फ्री चल रहा है सभी मेडिसन और सारा इलाज वहां से फ्री चल रहा है। सूरज शर्मा की पत्नी सोनिया शर्मा लोगों के घरों में काम करती है और 1500 सौ से ₹2000 तक कमा लेती है उनकी बीमारी के बाद ही सूर्य शर्मा जी की पत्नी ने मजबूरी में यह काम करना शुरु किया है। सूर्य शर्मा की एक बेटी वंशिका 5 साल की है और एक लड़का वंश 7 साल का है। कृष्ण कन्या स्कूल, नजदीक साईं मंदिर अपोजिट सोहन हलवाई, नमक मंडी अमृतसर में पढ़ते हैं। बेटी प्ले पैन में है और बेटा पहली कक्षा में पढ़ता है। सूरज शर्मा जब ठीक थे तो वह किसी की रेडी पर काम करते थे शादियों शादी में फ्रूट स्टाल भी लगाने जाते थे लेकिन अब कैंसर होने के कारण वह पिछले 1 साल कुछ भी नहीं कमा पा रहे हैं। जिस मंदिर के कमरे में वो रह रहे हैं उस मंदिर से उनको थोड़ी बहुत हेल्प मिल जाती है। सूरज शर्मा जी के माता पिता का भी पिछले 1-2 सालों में देहांत हो चुका है। उनका कोई भी रिश्तेदार उनकी मदद नहीं कर पा रहा। वह लेट्स हेल्प से राशन और बच्चों की फीस की आस रख रहे हैं। सभी सदस्यों से हाथ जोड़कर अनुरोध है कृपा ऊपर दिए गए मैसेज को ध्यान से पढ़ें और हमें आज्ञा दें कि हम सूरज शर्मा को राशन और बच्चों की फीस मुहैया करा सकें धन्यवाद',
    gender: 'm',
    age: 32,
    address: 'नमक मंडी, बड़ा मंदिर, तबेला जगतराम',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '7508129724',
    referredOn: '02/21/2018',
    approvedOn: '02/21/2018',
    title: 'spent for ration of Mr. Suraj Sharma (Cancer patient)',
    caseType: 'ration',
    name: 'Suraj Sharma',
    contactRelation: 'self',
    contactPerson: 'Suraj Sharma',
    gender: 'm',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '7508383015',
    referredOn: '03/10/2108',
    approvedOn: '03/10/2108',
    title: 'spent for the medicine of Ms. Komal (TB & Heart patient admitted at TB hospital )w/o Mr. Deepak',
    caseType: 'ration',
    name: 'Deepak Kumar',
    contactRelation: 'self',
    contactPerson: 'Deepak Kumar',
    description: 'प्यारे सदस्यों नीचे दिया गया यह केस हमारे आदरणीय मेंबर मनदीप सिंह जी द्वारा रेफर किया गया है। कोमल पत्नी दीपक कुमार जो कि इंदिरा कॉलोनी chabal रोड नजदीक रविदास मंदिर अमृतसर में रहते हैं। दीपक जी का मोबाइल नंबर 7508383015 है। दीपक कुमार बोरिया सीने का काम करते हैं उनकी मंथली इनकम 6000 से 7000 तक है। उनके घर कोई भी औलाद नहीं है। दीपक के माता पिता बीमार है और घर पर ही रहते हैं। कोमल को TB है और हार्ट की भी प्रॉब्लम है उनको पहले से सुनाई बी नहीं देता था वह इस समय चेस्ट एंड टीबी हॉस्पिटल अमृतसर में इमरजेंसी वार्ड में बेड नंबर 14 पर दाखिल है कोमल की उम्र 22 साल की है उनका भाई नवीन (9877931398)जो कि किसी दुकान पर काम करता है थोड़ी बहुत हेल्प कर रहा है क्योंकि उनको हार्ट की प्रॉब्लम है वह उस पर काफी पैसा लगा चुके हैं इस समय उनकी माली हालत बहुत खराब है और Let\'s Help से मदद चाहते हैं कृपया हमारा मार्गदर्शन कीजिए। धन्यवाद',
    gender: 'm',
    age: 22,
    address: 'इंदिरा कॉलोनी chabal रोड नजदीक रविदास मंदिर अमृतसर',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9814958170',
    referredOn: '04/03/2018',
    approvedOn: '04/03/2018',
    title: 'spent for Mr. Rakesh kumar brother of Sanjay medicine.( Albumin injection ',
    caseType: 'ration',
    name: 'Rakesh Kumar',
    contactRelation: 'self',
    contactPerson: 'Rakesh Kumar',
    description: 'प्यारे सदस्यों, नीचे दिया गया केस हमारे आदरणीय मेंबर श्री गुलशन शर्मा जी और बृजमोहन जी द्वारा रेफर किया गया है। राकेश कुमार, जिनकी उम्र 43 वर्ष है, लिवर की प्रॉब्लम से ग्रसित है जो कि भगत सिंह कॉलोनी, चौपाल रोड, नजदीक मिटा करियाना स्टोर, अमृतसर मैं किराए के मकान में रहते हैं जिस का किराया 2500 है। राकेश कुमार जी के पिता दीवान चंद का चूल्हा टूटा हुआ है और उन्हें पैरालाइज अटैक भी हुआ हुआ है और उनके शरीर का एक हिस्सा नहीं चलता एक साइड नहीं चलती और वह बुजुर्ग भी है बहुत है। राकेश कुमार जी की बहन अपाहिज (फिजिकली हैंडीकैप्ड) है उनकी दोनों टांगे नहीं चलती राकेश कुमार जी का भाई संजय अमृतसर में ढाब में लेबर का काम करता है और वह 8 से 10000 तक कमाते है संजय जी का मोबाइल नंबर 9814958170 है। विकलांग बहन को कभी कबार सलाई का काम आ जाता है जिससे वह कभी कबार 2-3 हजार कमा लेती हैं। लेकिन इस समय राकेश कुमार जो कि पहले हलवाई का काम करते थे लिवर में और पेट में पानी भर जाने के कारण गुरु नानक हॉस्पिटल में वार्ड नंबर 7, बेड नंबर 23, डॉक्टर तरसेम पाल जी की वार्ड में दाखिल है और उनकी हालत बहुत गंभीर है। राकेश कुमार जी पिछले 2 वर्ष से बीमार है। घरवालों वाले उनका और पिताजी का इलाज करवाने में सक्षम नहीं है। उनके भाई संजय ने अपने मालिक से ₹50000 उधार लेकर इलाज करवा रहे हैं। लेटेस्ट हेल्प से कुछ दवाइयों की मदद चाहते हैं कृपा हमें ऐसा करने की आज्ञा दें। आप सभी से हाथ जोड़कर विनती है कि हमारा मार्गदर्शन करें। धन्यवाद।',
    gender: 'm',
    age: 43,
    address: 'भगत सिंह कॉलोनी, चौपाल रोड, नजदीक मिटा करियाना स्टोर, अमृतसर',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9780416302',
    referredOn: '07/14/2018',
    approvedOn: '07/14/2018',
    title: 'spent for Master Shiv son of Mr. Naveen 9780416302 Case was referred by our member Mr. Mandeep ji',
    caseType: 'ration',
    name: 'Naveen',
    contactRelation: 'self',
    contactPerson: 'Naveen',
    description: 'प्यारे सदस्य, नीचे दिया गया केस हमारे आदरणीय मेंबर श्री मनदीप सिंह(9803019200) जी द्वारा दिया गया है। श्री मनदीप सिंह जी की दुकान पर एक लड़का नवीन (mobile no. 9780416302) काम करता है जो कि 95500/9 गली मोचया वाली, नियर जंग किराना स्टोर, गेट हकीमां वाला अमृतसर में रहता है ।जिनका मकान अपना है । नवीन जी का बेटा शिव जो कि 3 वर्ष का है प्ले पेन स्कूल में पढ़ता है लेकिन सोमवार से वह डॉक्टर गुरशरण, तेज नगर, अंतर्यामी कॉलोनी तरनतारन रोड, अमृतसर में दाखिल है डॉक्टर ने बताया है उसका खून सिर्फ 4 ग्राम रह गया है। नवीन जी के पिताजी श्री मदन लाल एक्सपायर कर चुके है नवीन जी के माता लोगों के घरों में बर्तन साफ करते हैं नवीन जी की पत्नी हाउसवाइफ है नवीन जी की सैलरी 5500 है। लगभग 1 हफ्ते से हॉस्पीटल में दाखिल होने का कारण उनका हॉस्पिटल का बिल 15000 से 20000 पर बन चुका है उनके मालिक मनदीप जी ने डॉक्टर से बात की है कुछ कंसेशन डॉक्टर से मिल जाएगा और कुछ मनदीप जी कंट्रीब्यूट करेंगे मनदीप जी चाहते हैं की कुछ मदद 2000- 3000 की लाइट्स हेल्प भी कर दे हम आपसे अनुरोध करते हैं कृपया हमारा मार्गदर्शन कीजिए।',
    gender: 'm',
    address: '95500/9 गली मोचया वाली, नियर जंग किराना स्टोर, गेट हकीमां वाला अमृतसर',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '8437996428',
    referredOn: '06/10/2018',
    approvedOn: '06/10/2018',
    title: 'Spent for Master Sukhman Singh (Amputated leg) Amandeep Hospital charges',
    caseType: 'ration',
    name: 'Sukhman Singh',
    contactRelation: 'self',
    contactPerson: 'Sukhman Singh',
    description: 'प्यारे सदस्यों, यह केस किसी अज्ञात व्यक्ति निर्वाल सिंह(Nirval Singh) मोबाइल नंबर 97813 29225 ने हमें कॉल करके बताया है उसने हमारा नंबर किसी से लिया है किसी ने हमारा नंबर उसको दिया था! 12 वर्ष लड़का सुखमन सिंह पिता का नाम प्रगट सिंह गांव इबन खुर्द नजदीक गुरु वाली तहसील अमृतसर मोबाइल नंबर 8437996428 है सुखमन सिंह सातवीं कक्षा का विद्यार्थी है।वह SDM मॉडल स्कूल गुरु वाली मोड,तरनतारन रोड, अमृतसर में पड़ता है जब वह स्कूल से आ रहा था तो उसकी वैन का 5 जून 2018 को एक्सीडेंट हो गया उसके पिता ने उसे गुरु राम दास हॉस्पिटल वल्ला दाखिल करवाया लेकिन हालत गंभीर होने के कारण उन्होंने उससे अमनदीप हॉस्पिटल दाखिल करवाया है वहां वह आईसीयू में बैड नंबर 15 पर दाखिल है वहां पर उसकी एक टांग काट दी गई है बच्चे के चूल्हे में भी फैक्चर है और उसकी रीड की हड्डी में भी प्रॉब्लम आ गई है सुखमन के पिता प्रगट मिस्त्रियों के साथ मजदूरी का काम करते हैं उसकी माता घरों में काम करती है उनके घर की आमदनी महीने की 10000 से 11000 पर है प्रगट जी का एक और बेटा भी है जो कि 15 वर्ष का है और आठवीं कक्षा में पढ़ता है। प्रगट के एक भाई की मृत्यु हो चुकी है उसके भाई के परिवार क�� बोझ भी प्रगट सिंह पर है परगट सिंह का एक भाई मेंटली अबनॉर्मल है परगट सिंह के पिताजी की मृत्यु हो चुकी है उनके बच्चे का इलाज कुछ संस्थाएं, गांव के लोग और साबका सरपंच निर्वाल सिंह Nirval Singh (जिसने हमें कॉल की है ) वह लोग मिलकर कर रहे हैं वह लोग लेट्स हेल्प से भी कुछ मदद चाहते हैं कृपया हमारा मार्गदर्शन कीजिए',
    gender: 'm',
    age: 12,
    address: 'गांव इबन खुर्द नजदीक गुरु वाली तहसील अमृतसर ',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9878697255',
    referredOn: '07/17/2018',
    approvedOn: '07/17/2018',
    title: 'spent on Kavita Thakur( gall stones patient)w/o Sh. Ravinder Thakur',
    caseType: 'ration',
    name: 'Kavita Thakur',
    contactRelation: 'self',
    contactPerson: 'Kavita Thakur',
    description: 'प्यारे सदस्य, कविता ठाकुर पत्नी श्री रविंद्र ठाकुर हाउस नंबर 123/ 11, गली माटी वाली , चरसती अटारी चौक, नजदीक ऊंचा शिवाला अमृतसर मोबाइल no husband (9878697255) Mother in law mobile no. (6280294560) कविता जी के पित्ते में पथरी है कविता जी डॉक्टर पवन भाटिया के अपोलो हॉस्पिटल में रूम नंबर 11 में दाखिल है कविता जी के दो बच्चों का देहांत हो चुका है अब उनकी सिर्फ एक ही पुत्री है कुछ समय पहले कविता जी के ससुर श्री संतोष कुमार को लीवर का कैंसर था श्री संतोष कुमार जी का भी देहांत हो चुका है लेट्स हेल्प ने उस समय भी इनकी कुछ मदद की थी लेकिन पहली बार मदद देने के कुछ दिन बाद ही उनका देहांत हो गया था(please it\'s for ur kind information) उनका एक बच्चा वासु जिस को दिमाग की कोई बीमारी थी उसका भी दिसंबर 2017 में देहांत हो चुका है और कविता जी के पति रविंद्र ठाकुर जी को भी गले का कैंसर था इन तीनों के इलाज में पिछले 2 साल से 10-12 लाख लगा चुके हैं उनका पति पहले नौकरी करते थे अब वही e- रिक्शा चलाते हैं उनके पत्ते के ऑपरेशन के लिए डॉक्टर ने 20000 ऑपरेशन का और दवाइयां अलग से बताए हैं क्योंकि वह पहले ही अपने ससुर पति और बच्चे पर काफी पैसा लगा चुके हैं वह अब इतना पैसा नहीं दे पा रहे और वह let\'s help से कुछ मदद चाहते हैं कृपया हमारा मार्गदर्शन कीजिए',
    gender: 'f',
    address: 'हाउस नंबर 123/ 11, गली माटी वाली , चरसती अटारी चौक, नजदीक ऊंचा शिवाला अमृतस',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '8054268306',
    referredOn: '07/17/2018',
    approvedOn: '07/17/2018',
    title: 'spent for Mr. Rajinder Kumar (8054268306) ( Rs.530 for Medicine and + Rs.700 for Echocardiography = Total 1230 ) Preet Hospital Ratan singh chowk Near petrol pump. Ph.9814741218 (Tran-Taran)',
    caseType: 'ration',
    name: ' Rajinder Kumar',
    contactRelation: 'self',
    contactPerson: ' Rajinder Kumar',
    description: 'आदरणीय सदस्यों, नीचे दिया गया केस हमारे आदरणीय मेंबर श्री प्रदीप कुमार जी(9463569833) द्वारा दिया गया है राजेंद्र कुमार सुपुत्र श्री रामकृष्ण निवासी प्लॉट नंबर 271, गली नंबर 09, इंदिरा कॉलोनी, नजदीक सरदारी लाल का भट्ठा, कोट खालसा, अमृतसर मोबाइल नंबर (8054268306) कुछ समय पहले रजिंदर जी के कान में फुंसी हुई थी उस समय इसका सही इलाज ना करने के कारण उसकी पस दिमाग तक चली गई अब वह दिमाग की प्रॉब्लम से ग्रसित है कान के द्वारा उनके दिमाग का ऑपरेशन हो चुका है लेकिन कुछ फर्क नहीं पड़ा अब रजिंदर जी की हालत बहुत खराब है काफी समय से बेड पर ही है उनको दिमाग के दौरे भी पड़ते हैं जब वह ठीक थे तो वह किसी फैक्ट्री में काम करते थे लेकिन अब उनकी हालत इतनी खराब है कि वह काम पर नहीं जा सकते राजेंद्र जी की पत्नी रजनीबाला घर पर ही काम करती है वह शॉल के धागे काटने का काम करती है जिससे उनको 1 शौल के ₹5 मिलते हैं और काम भी ज्यादा नहीं होता है राजेंद्र जी की हालत इतनी नाजुक है कि वह उनको छोड़कर बाहर भी काम करने नहीं जा सकती राजेंद्र जी की बूढ़ी मां किसी फैक्ट्री में काम करती है वह वहां से ₹2000 कमा कर ला पाती है राजेंद्र जी की पत्नी जो घर पर शॉल के धागे तोड़ने का काम करती है महीने का सिर्फ ₹500 कमाती है राजेंद्र जी के पिताजी का देहांत हो चुका है राजेंद्र जी के तीन बच्चे हैं एक लड़की 14 साल की 9 वीं कक्षा में पढ़ती है और दो लड़के जो की जुड़वा है 12 साल के दोनों सातवीं कक्षा में पढ़ते हैं एक छोटा सा दो कमरे का कच्चा मकान अपना है राजेंद्र जी की दवाइयों का खर्चा राशन और बच्चों का की पढ़ाई का खर्चा कर पाना बहुत मुश्किल हो गया है जब हमने उनके घर पर विजिट किया तो उनकी पत्नी ने हमें बताया कि हम फीस ना देने के कारण स्कूल से हो सकता है कि बच्चों को उठाना पड़े और इनकी दवाइयों का खर्चा भी करने में हम सक्षम नहीं है उन्होंने यह बताया कि अड़ोस-पड़ोस और कुछ रिश्तेदार हमें कभी कबार राशन डाल देते हैं और उनके इलाज के लिए उसने ₹8000 का कर्जा भी ले रखा है तू इस तरह से यह फैमिली बहुत दिक्कत में है लेट्स हेल्प इनकी मदद करना चाहता है कृपया हमें ऐसा करने की अनुमति दीजिए',
    gender: 'm',
    address: 'प्लॉट नंबर 271, गली नंबर 09, इंदिरा कॉलोनी, नजदीक सरदारी लाल का भट्ठा, कोट खालसा, अमृतसर',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '8054268306',
    referredOn: '10/15/2018',
    approvedOn: '10/15/2018',
    title: 'No Title',
    caseType: 'ration',
    name: ' Rajinder Kumar',
    contactRelation: 'self',
    contactPerson: ' Rajinder Kumar',
    description: 'आदरणीय सदस्यों, आप सब को पता है कि हमारे Let\'s Help की तरफ से श्री Rajinder Kumar पुत्र श्री रामकृष्ण निवासी प्लाट नंबर 271 गली नंबर 09 इंदिरा कॉलोनी नजदीक सरदारी लाल का भट्ठा कोट खालसा अमृतसर मोबाइल नंबर (8054268306) जोकि दिमाग से संबंधित किसी बीमारी से ग्रसित है, उनको हमारे लेटस हेल्प की तरफ से दवाइयों की सहायता की जा रही है। इस दिक्कत की वजह से वो कोई काम नही कर पा रहे है उनकी इस बीमारी के कारण उनकी माता जी किसी फैक्ट्री मे��� काम करती है दिक्कत ज्यादा होने के कारण अब उनकी पत्नी ने भी किसी के घर पर कपड़े बर्तन धोने का काम शुरू कर दिया है श्री राजिंदर जी के तीन बच्चे है ! जिनका नाम है (1) भावना 9वी कक्षा (2) कारण 7वी कक्षा ( 3) कृष 7वी कक्षा में पढ़ते है जो कि तीनों कोट खालसा के आरती पब्लिक स्कूल में पढ़ते है तीनों बच्चों की फीस पिछले 6 महीनों से नही दी गई है जिनकी कुल फीस 10015 रुपये हो गई है जो भरी नही गई है। जिससे स्कूल वालो की तरफ से बार-बार फ��स लाने को कहा जा रहा है लेकिन वो फीस देने में असमर्थ है। अब ये नौबत आ गई है की बच्चो को स्कूल से उठाना पड सकता है । वह हमारे लेटस हेल्प की तरफ से फीस संबंधी सहायता चाहते है। इसलिए आप सभी सदस्यो से अनुरोध है कि आप सब ऐसा करने की अनुमति दे धन्यवाद ।',
    gender: 'm',
    address: 'प्लॉट नंबर 271, गली नंबर 09, इंदिरा कॉलोनी, नजदीक सरदारी लाल का भट्ठा, कोट खालसा, अमृतसर',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '8054268306',
    referredOn: '03/17/2020',
    approvedOn: '03/17/2020',
    title: 'No Title',
    caseType: 'ration',
    name: ' Rajinder Kumar',
    contactRelation: 'self',
    contactPerson: ' Rajinder Kumar',
    description: '*आदरणीय सदस्यों, नमस्कार, हमारा यह आज का केस हमारे आदरणीय मेंबर श्री प्रदीप कुमार जी (9592929096) द्वारा दिया गया है। *सबसे पहले हम आपको यह अवगत करवा देना चाहते हैं यह केस वाले व्यक्ति को आप लोग हर महीने दवाई प्रोवाइड करवा रहे हैं।* राजेंद्र कुमार (8054268306) पुत्र श्री रामकृष्ण, प्लॉट नंबर 271, गली नंबर 9, इंदिरा कॉलोनी, नजदीक सरदारी लाल का पट्ठा, कोट खालसा, अमृतसर, के निवासी है। राजेंद्र कुमार के ब्रेन में कोई दिक्कत थी जोकि पिछले 2 साल से दवाई खा रहे हैं राजेंद्र जी के तीन बच्चे हैं। एक बेटी दसवीं क्लास में पढ़ती है। दो बेटे आठवीं कक्षा में पढ़ते हैं। जैसे कि आप लोगों को मालूम है रजिंदर कुमार जी पिछले 2 सालों से ठीक नहीं है वह अपने तीनों बच्चों की 2 साल की फीस नहीं दे पाए। इसके चलते उनके बच्चों की स्कूल फीस बहुत ज्यादा एकत्रित हो गई है। जो कि वह नहीं दे सकते। अब रजिंदर जी की हालत थोड़ी ठीक होने के साथ उन्होंने कुछ दिनों से किसी हलवाई की दुकान पर काम काम करना शुरू कर दिया है। उ���की पत्नी रजनी बाला लोगों के घरों में काम करती है। रजिंदर के माताजी भी किसी फैक्ट्री में काम करते थे लेकिन अब वह बहुत ज्यादा वृद्ध हो जाने के कारण अब नहीं कर रहे। राजेंद्र जी की बेटी भावना जो कि दसवीं कक्षा में है उससे कुछ बोर्ड के एग्जाम होने के कारण उसे कुछ फीस देखकर एग्जाम में बैठने में सहायता होगी। तीनों बच्चों को पिछले 2 साल से फीस ना देने के बावजूद भी प्रिंसिपल ने उनको शिक्षा दी,लेकिन अब बोर्ड की फीस और कुछ खर्चे मैं वह सहायता चाहते हैं कृपया हमें उनकी सहायता करने की आज्ञा दीजिए। Sorry ',
    gender: 'm',
    address: 'प्लॉट नंबर 271, गली नंबर 09, इंदिरा कॉलोनी, नजदीक सरदारी लाल का भट्ठा, कोट खालसा, अमृतसर',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9988778982',
    referredOn: '10/28/2018',
    approvedOn: '10/28/2018',
    title: 'spent for Ms. Jasbir Kaur W/O Mr. Kuljeet Singh (9988778982) For the operation of gall bladder stone operation at Mundh Hospital. Deposit above said money at hospital reception for Jasbir Kaur.',
    caseType: 'ration',
    name: 'Jasbir kaur',
    contactRelation: 'self',
    contactPerson: 'Jasbir kaur',
    description: 'आदरणीय सदस्यों, नीचे दिया हुआ केस हमारे आदरणीय सदस्य श्री प्रदीप कुमार जी द्वारा दिया गया है (9463569833) जसबीर कौर पत्नी कुलजीत सिंह, गली रेहड़ियां, नजदीक विश्कर्मा मंदिर, सोहन एवेन्यू, कोट खालसा, अमृतसर। (9988778982) जसबीर कौर के घर पर पांच सदस्य है। उनके पति कुलजीत सिंह जो साइकल पर फेरी लगाकर पापड़ वाडिया बेचने का काम करते है । जो महीने में 5000-6000 रुपये कमा पाते है जिनको हार्ट की दिक्कत थी और इस समय diabetic के मरीज है ओर पिछले 5 महीनों से हाथ में जख्म होने के कारण वह काम नही कर पा रहे थे । उनकी पत्नी जसबीर कौर को पित्ते में पथरी है बेटी डॉक्टर की दुकान पर काम करती है । एक बेटी सिलाई का काम सीखती है उनके बेटे को हर्निया की दिक्कत है वी भी कभी काम करता है कभी नही वह किराये के मकान में रहते है जिसका किराया 1500 रुपये है । सब सदस्य की आमदनी कुल मिलाकर 9000 रुपये के लगभग है । जसबीर कौर की पथरी का ऑपरेशन Mundh Hospital, Ranjit Avenue, Amritsar से करवाना चाहते है । जसबीर कौर का खून 6 ग्राम है इसलिए डॉक्टर ने उन्हें 17000 रुपये ऑपरेशन के खर्च बताया है और कुल।मिलाकर 23000, से 25000 रुपए का खर्च आने का अनुमान है । इसलिये वह लेटस हेल्प से 10000 रुपये को मदद चाहते है । आप सभी सदस्यों से हाथ जोड़कर विनती है की हमें उन्हें ₹10000 की सहायता देने की आज्ञा दीजिए। धन्यवाद',
    gender: 'f',
    address: 'गली रेहड़ियां, नजदीक विश्कर्मा मंदिर, सोहन एवेन्यू, कोट खालसा, अमृतसर',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9781929898',
    referredOn: '07/21/2019',
    approvedOn: '07/21/2019',
    title: 'spent for hospital and medicine for treatment of Ms. Tara Devi',
    caseType: 'ration',
    name: 'Tara Devi',
    contactRelation: 'self',
    contactPerson: 'Tara Devi',
    description: 'आदरणीय सदस्यों, नमस्कार हमारा आज का यह केस हमारे आदरणीय मेंबर श्री प्रदीप जी (9463569833)द्वारा दिया गया है। तारा देवी 72 वर्षीय बुजुर्ग जो कि केयर ऑफ मनजीत सिंह, 96, भारत नगर, बटाला रोड, अमृतसर के निवासी है।(9781929898) यह मोबाइल नंबर उनकी बेटी का है। तारा देवी किराए के मकान में रहते हैं। उनकी सभी लड़कियां एक को छोड़कर विवाहित है। एक लड़की जो उनके साथ रहती है वह विकलांग है। कमर से नीचे का सारा हिस्सा उन का कटा हुआ है। विकलांग बेटी सिलाई कटाई का काम करके घर का गुजारा करती हैं। तारा देवी का एक बेटा है जोकि यूपी के गांव में रहता है जिसकी भी माली हालत इतनी अच्छी नहीं है और वह भी उनकी मदद नहीं कर पा रहा। तारा देवी के पति भी बुजुर्ग होने के कारण कोई काम नहीं कर पाते उनके घर की विकलांग लड़की द्वारा सिलाई कढ़ाई करके महीने की कमाई 5000 है। तारा देवी का हिप में फ्रैक्चर होने के कारण हॉस्पिटल में दाखिल है उनको हार्ट की प्रॉब्लम है, शुगर है, दिमाग में clot है और किडनी में भी प्रॉब्लम है जितना खर्चा डॉक्टर्स ने बताया है उनका परिवार जे अफोर्ड नहीं कर पा रहा उनकी एक बेटी ने अपनी गोल्ड चेन गिरवी रख कर पैसे इकट्ठे कर अपनी मां को इलाज में दिए हैं। इन हालातों के चलते लेट्स हेल्प से कुश ऑपरेशन में कुछ मदद चाहते हैं कृपया हमें ऐसा करने की अनुमति दी जाए। धन्यवाद',
    gender: 'f',
    age: 72,
    address: 'केयर ऑफ मनजीत सिंह, 96, भारत नगर, बटाला रोड, अमृतसर',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '8195970751',
    referredOn: '08/25/2018',
    approvedOn: '08/25/2018',
    title: 'Brain tumour patient Rs.10,000 (Ten thousand only) Deposited at Akashdeep hospital reception for Mr. Dalbir Singh(brain tumour patient) s/o Mr. Sham lal. Mob no.8195970751',
    caseType: 'ration',
    name: 'Dalbir Singh',
    contactRelation: 'self',
    contactPerson: 'Dalbir Singh',
    description: 'प्रिय सदस्यों, नमस्कार, इस SMS के द्वारा हम आपको एक पेशेंट दलबीर सिंह पुत्र श्री श्यामलाल VPO वडाला, आबादी धरमपुरा, तहसील मजीठा, डिस्टिक अमृतसर | (मजीठा से फतेहगढ़ चूड़ियां लिंक रोड के सेंटर में जो गांव है.) मोबाइल नंबर 8195970751 से अवगत करवाना चाहते हैं। दलबीर सिंह उम्र 35 साल जो कि वडाला गांव में नाई का काम करता है और महीने के 8-9 हजार रुपया कमा पाते हैं। कुछ दिन पहले उनके सिर में दर्द हुआ और वह अचानक बेहोश हो गए डायग्नोसिस से पता चला की उनको ब्रेन ट्यूमर है। बहुत से हॉस्पिटलों में इलाज करवाने के बाद अब वह अकाशदीप हॉस्पिटल मजीठा रोड अमृतसर में आईसीयू बेड नंबर 4 में दाखिल है उनके इलाज पर बहुत खर्चा हो रहा है जो कि वह करने में सक्षम नहीं है उन्होंने अपने घर का सारा सोना भी बेचकर एक लाख रुपैया हॉस्पिटल में जमा करवा दिया है। एक संस्था दसवंद सेवा सोसाइटी ने उन्हें ₹10000 दिया है किसी और सोसाइटी रुपाणा सेवा सोसायटी ने भी ₹11000 दिया है लेकिन फिर भी पैसे कम पड़ रहे हैं दलबीर सिंह जी की पत्नी हाउसवाइफ है दलबीर सिंह जी के तीन बच्चे हैं दो बेटियां और एक बेटा ।दलबीर सिंह जी का गांव में अपना मकान है। गुरप्रीत सिंह जी ने हमें फोन 9888075151 करके यह केस रेफर किया है। दलबीर जी का भतीजा राणा जो कि हॉस्पिटल में उनकी देखरेख करा है हमारे संपर्क में है उनका मोबाइल नंबर8728940001 है। हम आप लोगों से अनुमति चाहते हैं की हम दलबीर सिंह की मदद कर सके आप लोगों से विनती है की दलबीर सिंह की मदद करने के लिए हमें अनुमति दीजिए धन्यवाद हमारे मेंबर सरदार जितेंद्र सिंह जी के हम अति आभारी हैं कि उन्होंने अपना कीमती समय निकालकर इस केस के बारे में इंफॉर्मेशन एकत्रित करने में हमारी मदद की धन्यवाद जितेंद्र जी',
    gender: 'm',
    age: 35,
    address: 'VPO वडाला, आबादी धरमपुरा, तहसील मजीठा, डिस्टिक अमृतसर | (मजीठा से फतेहगढ़ चूड़ियां लिंक रोड के सेंटर में जो गांव है.)',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9914201061',
    referredOn: '09/07/2018',
    approvedOn: '09/07/2018',
    title: 'Case by JM Arora',
    caseType: 'ration',
    name: 'Arshdeep Kaur',
    contactRelation: 'self',
    contactPerson: 'Arshdeep Kaur',
    description: 'प्रिय सदस्यों, हम सरदार जितेंद्र सिंह(9872947885) हमारे आदरणीय मेंबर के बहुत आभारी हैं जिन्होंने अपना कीमती समय निकालकर नीचे दी गई जानकारी एकत्रित करने में हमारी मदद की। आज का यह केस हमारे आदरणीय मेंबर श्री JM Arora (9815645403) जी द्वारा दिया गया हैl के JM अरोड़ा जी को यह केस उनके मित्र सरदार जितेंद्र सिंह जी ने बताया है(9988428586) अर्शदीप कौर बच्ची जिसकी उम्र 15 वर्ष है कुछ महीने पहले उसके पिताजी और दादाजी दोनों का देहांत हो गया है अर्शदीप कौर के माताजी ज्ञान कौर (9914201061)लोगों के घरों में गांव में काम करती है अर्शदीप कौर अर्शदीप का एक भाई दोनों गांव के गवर्नमेंट स्कूल में पढ़ते हैं। अर्शदीप पिंड कोटली, डोलेसरा, नजदीक जयंतीपुर डिस्टिक अमृतसर के निवासी हैं। अर्शदीप कौर की गुदा में कुछ प्रॉब्लम है जिससे उनके का लैट्रिन और बाथरूम दोनों रुके हुए हैं डॉक्टर्स ने तुरंत दो ऑपरेशन करवाने को कहा है अभी तक एक प्रशन हो चुका है दूसरा अभी होना है इस समय वह धारीवाल हॉस्पिटल बटाला रोड में एडमिट है अर्शदीप की माता को भी शरीर में बहुत प्रॉब्लम है उनको इतनी प्रॉब्लम है कि वह अक्षदीप के ऑपरेशन के लिए भी अमृतसर नहीं आ पाय उनकी एक बुआ कमलजीत कौर 7707939157 और उनके पति उनको अमृतसर में लाकर उनका इलाज करवा रहे हैं अर्शदीप कौर के माता फिजिकली ठीक ना होने के बावजूद भी लोगों के घरों में काम करते हैं और वो ऑपरेशन कराने में सक्षम नहीं है जैसा कि हमें उन्होंने बताया कि एक संस्था ने ₹30000 की मदद दी है। उन्होंने गांव के गुरुद्वारे से भी मदद के लिए अनाउंसमेंट करवाई है। जिस स्कूल में अर्शदीप पड़ती है वहां भी उन्होंने मदद के लिए कहा है लेकिन एक सेवा समिति के अतिरिक्त अभी तक कोई मदद नहीं हो पाई। वह लेट्स हेल्प से कुछ मदद चाहते हैं कृपा हमें ऐसा करने की अनुमति दीजिए धन्यवाद।',
    gender: 'f',
    age: 15,
    address: 'पिंड कोटली, डोलेसरा, नजदीक जयंतीपुर डिस्टिक अमृतसर',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '7508232529',
    referredOn: '09/27/2018',
    approvedOn: '09/27/2018',
    title: 'Abnormal child. spent for Gobind medicine',
    caseType: 'ration',
    name: 'Gobind',
    contactRelation: 'self',
    contactPerson: 'Gobind',
    gender: 'm',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9646408596',
    referredOn: '10/29/2018',
    approvedOn: '10/29/2018',
    title: 'Spent for ration for Mr. Guljeet Singh',
    caseType: 'ration',
    name: 'Guljeet Singh',
    contactRelation: 'self',
    contactPerson: 'Guljeet Singh',
    description: 'आदरणीय सदस्यों नमस्कार, आज का यह केस श्री नवनीत कुमार (798689893) और हमारे आदरणीय मेंबर श्री मनप्रीत सिंह जी(9855622915) द्वारा दिया गया है गुलजीत सिंह पुत्र श्री उधम सिंह L- 13/ 355, 19A आबादी महंत लक्ष्मण दास, सुल्तानविंड रोड अमृतसर के निवासी है। जिनका मोबाइल नंबर(9646408596) है। जिनका अपना मकान है। गुलजीत जी की दो बेटियां हैं और एक बेटा है। दोनों बेटियों की उन्होंने विवाह कर दिया है एक बेटी का कुछ दिन पहले विवाह किया जो कि किसी सोसाइटी द्वारा किया गया। गुलजीत जी का लड़का हरप्रीत सिंह किसी गारमेंट शॉप पर काम करता है जो कि महीने का ₹6000 कमा पाता है। गुलजीत सिंह जी खराद का काम करते थे उनकी बीवी हाउसवाइफ है। परिवारिक दिक्कतों के चलते उन्होंने अपने साले के बेटे की बेटी को अडॉप्ट किया हुआ है गुरजीत सिंह जी को रीड की हड्डी में कुछ प्रॉब्लम है जिस कारण वह पिछले 4 साल से बेड पर है और कोई काम नहीं कर सकते उन्हें 2-3 लाख का कर्जा भी ले रखा है। उनका परिवार दिक्कत में है क्योंकि वह पिछले 4 साल से बेडरिडेन है इसलिए दिन में एक दो बार उन्हें डायपर चेंज करने पड़ते हैं। अकेले डायपर का ही 1300 से 1500 तक का पूरे महीने का खर्चा आता है दवाइयों का खर्चा अलग है उनके घर की आमदनी सिर्फ 6000 है जो कि उनका लड़का दुकान पर काम करके लाता है। वह लेट्स हेल्प से राशन और डायपर की सहायता चाहते हैं आप सभी से हाथ जोड़कर अनुरोध है कृपया हमारा मार्गदर्शन कीजिए।',
    gender: 'm',
    address: 'L- 13/ 355, 19A आबादी महंत लक्ष्मण दास, सुल्तानविंड रोड अमृतसर',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9646408596',
    referredOn: '10/29/2018',
    approvedOn: '10/29/2018',
    title: 'Spent for Diapers for Mr. Guljeet Singh',
    caseType: 'ration',
    name: 'Guljeet Singh',
    contactRelation: 'self',
    contactPerson: 'Guljeet Singh',
    gender: 'm',
    address: 'L- 13/ 355, 19A आबादी महंत लक्ष्मण दास, सुल्तानविंड रोड अमृतसर',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9810130207',
    referredOn: '10/28/2018',
    approvedOn: '10/28/2018',
    title: 'spent for ration of Mr. Vijender Singh',
    caseType: 'ration',
    name: 'Vijender singh',
    contactRelation: 'self',
    contactPerson: 'Vijender singh',
    description: 'Respected members, i want to request to help a family. Details are as below Vijender singh Mistri by job Address: faridabad, AC nagar, NIT.mobile number : 9810130207 He was working at the 32nd floor building and the support rope broke off when he was at 3rd floor repairing the building. He got injuries in the backbone and was advised complete bed rest by the doctoRs.His wife is working at a local factory but could not devote full time there as she had to take care of vijender because he is bed ridden and she left the job. All 5 daughters are studying, mother is old so cant work. He has managed his medical expenses but we wish to support him with ration( ration) till the time he gets physically equipped to start working again which doctors suggest that he should be fine in next 3 months. Please consider the above case and let us know if we can extend some help Vinod Jain Faridabad',
    gender: 'm',
    address: 'Faridabad, AC nagar, NIT',
    city: 'Faridabad',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9803832148',
    referredOn: '12/29/2018',
    approvedOn: '12/29/2018',
    title: 'spent for cancer patient Ms. Amarjeet Kaur admitted at GND Hosp, Amritsar, Surgery ward no 4, Bed no, 2',
    caseType: 'ration',
    name: 'Amarjeet Kaur',
    contactRelation: 'self',
    contactPerson: 'Amarjeet Kaur',
    description: 'प्यारे सदस्यों, आज का यह केस हमारे आदरणीय मेंबर श्री अमृत लाल (मोबाइल no 9780935243) जी द्वारा किया गया है। अमरजीत कौर 56 वर्षीय पत्नी स्वर्गीय श्री अजायब सिंह। रेजिडेंस ऑफ L8/49, गली नंबर 2 गुरु गोविंद सिंह नगर तरनतारन रोड, अमृतसर मोबाइल (9803832148) मैं रहते हैं। इनका का मकान अपना है। अमरजीत कौर बचपन से हीअपाहिज है। इस समय अमरजीत कौर ब्रेस्ट कैंसर से पीड़ित है, वह गुरु नानक हॉस्पिटल के सर्जरी वार्ड में दाखिल है। उनका बेटा हरप्रीत सिंह जो कि कड़े बनाने का काम करता है ₹12000 हर महीने कमा पाता है। पिछले 2 वर्ष से अमरजीत कौर को ब्रेस्ट के कैंसर की दिक्कत होने से उनका इलाज चल रहा है। उनके बेटे ने लगभग 2 लाख तक इस वक्त तक लगा चुके हैं। इसमें उन्होंने ₹70000 मकान गिरवी रख कर कर्जा लिया है। अब फिर वह गुरु नानक हॉस्पिटल में दाखिल है। अब भी उन्होंने 30000 का कर्जा लेकर इलाज करवा रहे हैं। अमरजीत कौर की दो बेटियां हैं और एक बेटा है। घर में कमाई का साधन सिर्फ उनका बेटा हरप्रीत सिंह ही है। ब्रेस्ट रिमूव करने का ऑपरेशन था उसके बाद किमो बी होगी। वह लेट्स हेल्प से मदद चाहते हैं हम आपसे अनुरोध करते हैं कि हमारा मार्गदर्शन कीजिए',
    gender: 'f',
    address: 'L8/49, गली नंबर 2 गुरु गोविंद सिंह नगर तरनतारन रोड, अमृतसर',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9803832148',
    referredOn: '12/29/2018',
    approvedOn: '12/29/2018',
    title: 'spent for cancer patient medicine of Ms. Amarjeet Kaur',
    caseType: 'ration',
    name: 'Amarjeet Kaur',
    contactRelation: 'self',
    contactPerson: 'Amarjeet Kaur',
    gender: 'f',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9780448283',
    referredOn: '01/20/2019',
    approvedOn: '01/20/2019',
    title: 'spent for Harkirat Kaur(17 year old cancer patient) d/o Mr. Jatinder pal Singh',
    caseType: 'ration',
    name: 'Harkirat Kaur',
    contactRelation: 'self',
    contactPerson: 'Harkirat Kaur',
    description: 'आदरणीय सदस्यों, आज का यह केस नवनीत कुमार जी मोबाइल नंबर (7986898931)द्वारा दिया गया है। 17 वर्षीय हरकीरत कौर सुपुत्री जितेंद्र पाल सिंह माता का नाम गुरिंदर कौर निवासी नजदीक भाई मनी सिंह गुरुद्वारा, गली नंबर 3, गुरु नानक कॉलोनी, तरनतारन रोड, अमृतसर के निवासी है मोबाइल नंबर 9780448283 जिनका अपना मकान है हरकीरत के पिता जी मोबाइल रिचार्ज की दुकान करते हैं। हरकीरत की माता हाउसवाइफ है। हरकीरत को बोन कैंसर है इससे उनके शोल्डर में ट्यूमर है जिनका अमृतसर एसजीआरडी हॉस्पिटल में इलाज चलता रहा है लेकिन अब वह टाटा हॉस्पिटल संगरूर में इलाज करवा रहे हैं अमृतसर में फ्री फाइल बनी होने के कारण अब संगरूर में दूसरी बार फ्री नई फाइल नहीं बन पा रही। पिछले समय से उनका बहुत पैसा बच्चे के कैंसर के इलाज में खर्च हो चुका है उन्होंने 3 लाख रुपए का लोन भी लेकर बच्चे पर लगा दिया है अब उनकी माली हालत ठीक नहीं है। हरकीरत की 18 कीमो हो चुकी है और अभी भी जारी है। कीमो होने के कारण उनको कानों में दिक्कत आ गई है और उनको सुनना बंद हो गया है।हरकीरत के मामा पी एस भल्ला जी का मोबाइल नंबर 9988740321 हरकीरत का परिवार लेट्स हेल्प से कुछ मदद चाहते हैं कृपया हमें ऐसा करने की अनुमति दीजिए',
    gender: 'f',
    age: 17,
    address: 'निवासी नजदीक भाई मनी सिंह गुरुद्वारा, गली नंबर 3, गुरु नानक कॉलोनी, तरनतारन रोड, अमृतसर',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '6239855612',
    referredOn: '02/20/2019',
    approvedOn: '02/20/2019',
    title: '(Cancer patient) spent for school fees of late Mr. Suraj Sharma children',
    caseType: 'ration',
    name: 'Suraj Sharma',
    contactRelation: 'self',
    contactPerson: 'Suraj Sharma',
    gender: 'm',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '6239855612',
    referredOn: '02/20/2019',
    approvedOn: '02/20/2019',
    title: 'spent for school fees and admission fees of late Mr. Suraj Sharma children',
    caseType: 'ration',
    name: 'Suraj Sharma',
    contactRelation: 'self',
    contactPerson: 'Suraj Sharma',
    gender: 'm',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '7341169773',
    referredOn: '04/11/2019',
    approvedOn: '04/11/2019',
    title: 'spent for ration of Ms. Kanta Devi',
    caseType: 'ration',
    name: 'Kanta Devi',
    contactRelation: 'self',
    contactPerson: 'Kanta Devi',
    description: 'आदरणीय सदस्यों, नमस्कार। आज का हमारे यह केस आदरणीय सदस्य श्री राजेश शर्मा (8968127297)जी और श्री अजय कपूर जी(98555114557) द्वारा दिया है। कांता देवी पत्नी श्री कमल किशोर 55 वर्षीय विधवा है जोकि (फिजिकली हैंडिकैप्ड) अपंग है। हाउस नंबर T20, गली चाय वाली, नजदीक पीपल वाली गली, कटरा दुलो वाला, अमृतसर के निवासी हैं। ( मोबाइल नंबर 7341169773) कांता जी का के पति का देहांत हो चुका है। कांता जी का एक बेटा है जोकि नशे करता है। कांता जी की बहु उनके बेटे को छोड़कर चली गई है। कांता जी का बेटा किसी कपड़े की दुकान पर काम करता है। लेकिन वह काम पर कभी जाता है तो कभी नहीं जाता है। वह घर भी कांता जी के पास कभी आता है तो कभी नहीं आता है। कांता जी की एक बेटी है जो कि विवाहित है। उनका जवाई किसी की दुकान पर काम करता है। कांता जी कि सेहत ठीक ना होने के कारण वह भी काम नहीं कर पा रही। जिनसे उनकी माली हालत बहुत खराब है। जैसा उन्होंने बताया की माली हालत इतनी खराब है उन्होंने घर का सिलेंडर गिरवी रख कर 1700 रुपए उधार पकड़े हैं। इस वक्त वह छोटा सिलेंडर किसी से लेकर किलो के हिसाब से गैस भरवा कर काम चला रहे हैं। कांता जी का भाई पहले उनको हर महीने ₹500 देकर मदद करता था कुछ कारणों के चलते अब वह भी मदद नहीं कर पा रहा। कांता जी किराए के मकान में रहते हैं जिस का किराया ₹1800 है। *__कांता जी लेट्स हेल्प से हर महीने राशन की मदद चाहते हैं।__* हम आपसे विनती करते हैं कि अपने सुझाव व्यक्त करें *कृपया अपने सुझाव जरूर वह जरूर व्यक्त करा करें* । धन्यवाद',
    gender: 'f',
    age: 55,
    address: 'हाउस नंबर T20, गली चाय वाली, नजदीक पीपल वाली गली, कटरा दुलो वाला, अमृतसर',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '7341169773',
    referredOn: '04/11/2019',
    approvedOn: '04/11/2019',
    title: 'spent for LPG cylinder for Ms. Kanta Devi',
    caseType: 'ration',
    name: 'Kanta Devi',
    contactRelation: 'self',
    contactPerson: 'Kanta Devi',
    gender: 'f',
    age: 55,
    address: 'हाउस नंबर T20, गली चाय वाली, नजदीक पीपल वाली गली, कटरा दुलो वाला, अमृतसर',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9855511457',
    referredOn: '05/22/2019',
    approvedOn: '05/22/2019',
    title: 'spent for the ration of Mr. Bhajan Lal {Mr. Ajay Kapoor case (9855511457)',
    caseType: 'ration',
    name: 'Bhajan Lal',
    contactRelation: 'self',
    contactPerson: 'Bhajan Lal',
    description: 'प्रिय सदस्यों, नीचे दिया गया केस हमारे आदरणीय सदस्य श्री अजय कपूर जी द्वारा दिया गया है।(9877119936) (9855511457) भजन लाल पुत्र श्री रलिया राम नजदीक टेलर, संतनगर, अमृतसर के रहने वाले हैं। उनकी उम्र 72 साल है उनकी पत्नी की आयु 60- 65 वर्ष के बीच है वह भी बीमार रहती हैं वह एक किराए के मकान में रहते हैं जिस का किराया ₹1000 है। वह मुरमुरा, सील, गजक आदि बेचने का काम करते हैं। उनकी पत्नी का खून(HB) कम हो जाता है। वह ₹3000 महीने तक का कमा लेते हैं। उम्र ज्यादा होने के कारण वह रोज काम पर नहीं जा पाते। उनकी एक बेटी और एक बेटा है। बेटा जो की देहरादून में रहता है लेकिन वह अपने पिताजी की मदद नहीं करता है। उनकी बेटी और दामाद लेंटर गिरने के कारण बहुत बुरी तरह जख्मी हो गए हैं। इसलिए वह संस्था की तरफ से राशन की मदद चाहते हैं। आप सभी सदस्यों से निवेदन है कि आप हमें ऐसा करने की अनुमति दें। धन्यवाद हमारे दो सदस्यों श्री ऋषि जैन जी और श्री अजय कपूर जी इन दोनों सदस्यों ने उनके घर पर विजिट किया था वह एक गोदाम में रहते हैं भजन लाल जी के पास कोई भी मोबाइल नंबर नहीं है और उनके गोदाम का एड्रेस भी उन्हें अच्छे से नहीं मालूम जितनी जानकारी भी हमें मिली वह आपके सामने उपलब्ध है।',
    gender: 'm',
    age: 72,
    address: ' नजदीक टेलर, संतनगर, अमृतसर',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '7814399633',
    referredOn: '05/28/2019',
    approvedOn: '05/28/2019',
    title: 'spent for Ms. Usha M/O Mr. Naveen (7814399633) she is admitted at Civil hosp, Amritsar. Case referred by Mr. Mandeep Singh 9803109200',
    caseType: 'ration',
    name: 'Usha',
    contactRelation: 'self',
    contactPerson: 'Usha',
    description: 'प्रिय सदस्यों, नमस्कार आज का हमारा यह केस हमारे सदस्य सरदार मनदीप सिंह (9803109200)जी द्वारा दिया गया है। उषा नाम की औरत 55 वर्षीय जो कि गली मुचिया वाली, नियर जंग किराना स्टोर, नियर गवर्नमेंट स्कूल, गेट हकीमा वाला, अमृतसर के निवासी हैं मोबाइल नंबर(7814399633) उनका लड़का नवीन मनदीप जी की दुकान में काम करता है। वहां से वह रु 6000 प्रति महीना कमा पाते हैं नवीन जी का अपना मकान है नवीन के फादर का नाम मदनलाल है जिनका देहांत हो चुका हैं। इनका कोई भाई और बहन नहीं है उनकी माता उषा को फेफड़ों की टीबी है। कॉफी इलाज कराने के बावजूद वह ठीक नहीं हो पा रही, TB के चलते वह बहुत कमजोर हो चुकी हैं और उन्हें काफी महीनों से बुखार चल रहा है और बहुत ज्यादा कमजोरी हो गई है और अब भी लगातार बुखार रहता है घर में पैसे की दिक्कत होने के कारण वह उन्हें दाखिल नहीं करवा पा रहे वैसे तो टी बी की दवाई फ्री मिल रही है फिर भी हलात को देखते हुए उनको दाखिल कराकर इलाज होना चाहिए नवीन यह करने में सक्षम नहीं है उसने हमें बताया कि उसने रु 2500 बाजार से उधार पकड़कर लगा दिया है लेकिन अब उनके पास पैसे ना होने के कारण वह अपनी माता को दाखिल नहीं करा पा रहे नवीन की पत्नी भी उन्हें छोड़कर बच्चा लेकर चली गई है इन सब मुश्किलों के चलते यह परिवार बहुत ज्यादा दिक्कत में है यह परिवार लेट्स हेल्प से दवाइयों, टेस्ट और इलाज के लिए मदद चाहते हैं नवीन ने हमें बताया कि वह कुछ दिनों से गुरुद्वारा बाबा शहीदा से लंगर खा कर गुजारा कर रहा है हम सभी सदस्यों से अनुरोध करते हैं कृपया हमें इस परिवार की मदद करने की आज्ञा दें। धन्यवाद',
    gender: 'f',
    age: 55,
    address: 'गली मुचिया वाली, नियर जंग किराना स्टोर, नियर गवर्नमेंट स्कूल, गेट हकीमा वाला, अमृतसर',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '7814399633',
    referredOn: '07/14/2019',
    approvedOn: '07/14/2019',
    title: 'spent for Ms. Usha M/O Mr. Naveen (7814399633) for medicine and other charges',
    caseType: 'ration',
    name: 'Usha',
    contactRelation: 'self',
    contactPerson: 'Usha',
    gender: 'f',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9872964186',
    referredOn: '07/03/2019',
    approvedOn: '07/03/2019',
    title: 'spent for Master Sukhrajpreet Singh s/o S Jagdish Singh mobile no. 9872964186 For injections for 16 year old boy Above said case was referred by our respected member Mr. Mukesh Kumar 8360584903',
    caseType: 'ration',
    name: 'Sukhrajpreet Singh',
    contactRelation: 'self',
    contactPerson: 'Sukhrajpreet Singh',
    description: 'प्यारे सदस्यों, नमस्कार आज का हमारा यह केस हमारे आदरणीय मेंबर श्री मुकेश कुमार(8360584903) जी द्वारा दिया गया है। 16 वर्षीय सुखराज प्रीत सिंह सुपुत्र सरदार जगदीश सिंह (मोबाइल नंबर 9872964186) पक्की बन्नी वाली, सुल्तान विंड गांव, अमृतसर, के निवासी हैं। जो कि किराए के मकान में रहते हैं। मकान का किराया ₹3000 देते हैं। सुखराज प्रीत सिंह के पिता आटा चक्की की रिपेयर का काम करते हैं जो काम कभी आता है कभी नहीं आता है। सुखराज प्रीत सिंह के माता जी घर पर गुटका साहिब का परस बनाते हैं वह काम भी कभी आता है कभी नहीं आता है। तीन-चार दिन पहले सुखराज प्रीत सिंह जब खेल कर घर वापस आए तो उनको उठने में थोड़ी दिक्कत हुई धीरे धीरे उनके हाथ की पकड़ भी कम होती गई डॉक्टर को दिखाने पर पता चला कि नर्वस की प्रॉब्लम के कारण उन्हें एक तरह का पैरालाइज शुरू हो गया है। उनकी हालत बहुत गंभीर हो गई है। उनको एक दिन में ₹30000 के इंजेक्शन लग रहे हैं जोकि 5 दिन तक लगातार लगेंगे परंतु उसके पिता जगदीश सिंह यह सब करने में असमर्थ है यही काम उन्होंने पहले प्राइवेट हॉस्पिटल में दिखाया था उन्होंने सात से आठ लाख का खर्चा बताया था अब भी उनके सभी रिश्तेदार इकट्ठे होकर इन इंजेक्शन का प्रबंध कर रहे हैं जगदीश सिंह के पूरे परिवार की घर की इनकम 9 से ₹10000 प्रति महीना है इस समय वह बेबे नानकी हॉस्पिटल, गुरु नानक हॉस्पिटल, अमृतसर में 6th मंजिल में बच्चों की वार्ड में दाखिल है। बच्चे की हालत बहुत गंभीर है। डॉक्टरों ने बताया है कि अगर यह प्रॉब्लम उनके गले तक चली गई तो बहुत दिक्कत का कारण बन सकती है लेट्स हेल्प उन्हें 2 इंजेक्शन की मदद देना चाहते हैं जो कि लगभग ₹15000 के नजदीक होगा कृपया हमें ऐसा करने की अनुमति दीजिए। धन्यवाद।',
    gender: 'm',
    age: 16,
    address: ' पक्की बन्नी वाली, सुल्तान विंड गांव, अमृतसर',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9780418513',
    referredOn: '07/22/2019',
    approvedOn: '07/22/2019',
    title: 'spent for Mr. Parveen Arora(9780418513) medicine who is admitted at Nayyar hosp because of brain clot Above said case was referred by Mr. Ajay Kapoor ji(9855511457)',
    caseType: 'ration',
    name: 'Parveen Arora',
    contactRelation: 'self',
    contactPerson: 'Parveen Arora',
    description: 'आदरणीय सदस्यों, आज का हमारा यह केस हमारे आदरणीय मेंबर श्री अजय कपूर जी द्वारा दिया गया है (9855511457) 42 वर्षीय प्रवीण अरोड़ा सुपुत्र श्री नंदकिशोर अरोड़ा, हाउस नंबर 1047, गली सुनारिया, नमक मंडी, अमृतसर के वासी हैं। (9780418513) उनका मकान किराए पर है जिस का किराया 3500 रुपए प्रतिमाह है। प्रवीण अरोड़ा जी जो कि ड्राई फ्रूट का ब्रोकर का पार्टनरशिप में काम करते थे। उनकी पत्नी किसी डेंटल क्लीनिक पर हेल्पर का काम करती है। लेकिन अब बीमारी के चलते ना तो प्रवीण अरोड़ा जी काम पर जा पाते हैं और ना ही उनकी पत्नी। प्रवीण अरोड़ा जी के पिताजी बहुत ज्यादा वृद्ध है वह भी कोई काम नहीं कर सकते। प्रवीण अरोड़ा जी का एक बेटा 8 वीं कक्षा में पढ़ता है। प्रवीण अरोड़ा जी के ब्रेन में clot आ गया है और ब्लीडिंग भी है। पिछले 3 साल से इलाज चल रहा है और काफी पैसा इस इलाज में खर्च हो चुका है। कुछ समय वह ठीक रहे लेकिन अब फिर वह नैय्यर हॉस्पिटल अमृतसर में 2nd फ्लोर, जनरल वार्ड, बेड नंबर 5 में दाखिल है। डॉक्टर प्रभजीत सिंह जी का इलाज चल रहा है। पिछले 9 दिनों से वह नय्यर हॉस्पिटल में दाखिल हैं। उनकी बहनें और रिश्तेदार उनकी मदद कर रहे हैं। डॉक्टर प्रभजीत सिंह भी उनकी मदद कर रहे हैं। इस समय उनकी हालत गंभीर है वह लेट्स हेल्प से कुछ मदद चाहते हैं। कृपा हमें उनकी मदद करने की अनुमति दीजिए। धन्यवाद।',
    gender: 'm',
    age: 42,
    address: 'हाउस नंबर 1047, गली सुनारिया, नमक मंडी, अमृतसर',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9653475743',
    referredOn: '08/28/2019',
    approvedOn: '08/28/2019',
    title: 'spent for Ms. Harpreet Kaur w/o Mr. Pardeep Singh (Arms burn case)',
    caseType: 'ration',
    name: 'Harpreet Kaur',
    contactRelation: 'self',
    contactPerson: 'Harpreet Kaur',
    description: 'आदरणीय सदस्यों, नमस्कार आज का हमारा यह केस हमारे आदरणीय मेंबर श्रीमती जसप्रीत कौर जी (9988241741)द्वारा दिया गया है। हरप्रीत नाम की स्त्री जिसकी आयु 35 वर्षीय है उसके पति का नाम प्रदीप सिंह है। अरफ वाला मोहल्ला, नजदीक दुर्गा मंदिर, कपूरथला (मोबाइल नंबर 9653475743) किराए के मकान में रहते हैं। उनके मकान का रेंट 2200 प्रति महीना है। हरप्रीत कौर अपनी बेटी को गर्म पानी से नहला रही थी और गरम पानी उनके दाएं बाजू पर पड़ गया बेबी को बचाते-बचाते उनकी बाजू जल गई दिसंबर 2018 से उनका इलाज चल रहा है लेकिन उनका जख्म ठीक नहीं हो रहा है उन्होंने अपने बाजू पर कर्जा लेकर दो लाख से ऊपर का खर्चा कर दिया है लेकिन अभी भी जख्म ठीक नहीं हो रहा है। 1 महीने में ₹3000 की पट्टी जिसमें मेडिसन,पट्टी, कॉटन, बीटाडीन बगैरा आती है। हरप्रीत के पति किसी कपड़े की दुकान पर काम करते हैं। हरप्रीत खुद एक प्राइवेट स्कूल में पढ़ाती है। दोनों की कुल इनकम प्रति महीना 10000 के करीब है उन्होंने कर्जा लेकर उनकी बाजू का इलाज करवाया जैसा उन्होंने बताया अभी भी उन्होंने ₹30000 का कर्ज देना है उनकी बाजू के इलाज में हर रोज एक ट्यूब जिसकी कीमत ₹90 है जो कि 1 दिन में पूरी लग जाती है 1 महीने की 30 ट्यूबों की मदद लेट्स हेल्प से चाहते हैं क्योंकि वह घर के खर्चों के बाद बाजू का इलाज करवाने में दिक्कत आ रही है। हम आपसे अनुरोध करते हैं कृपा हमें हरप्रीत कौर की मदद करने की इजाजत दीजिए। आप सभी से अनुरोध है कि अपना विचार जरूर व्यक्त कीजिए। धन्यवाद',
    gender: 'f',
    age: 35,
    address: 'अरफ वाला मोहल्ला, नजदीक दुर्गा मंदिर, कपूरथला',
    city: 'Kapurthala',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9417950886',
    alternateNo1: '9988423440',
    referredOn: '10/18/2019',
    approvedOn: '10/18/2019',
    title: 'spent for medicine and hospital charges for operation for Mr. Ashan Masih {Leg ulcers case} Case referred by Mr. Chetan Arora 94179-50886 Ms. Rupali Madan 75087-20852 Mr. Ravinder Sharma 99884-23440 (9988423440)',
    caseType: 'ration',
    name: 'Ashan Masih',
    contactRelation: 'self',
    contactPerson: 'Ashan Masih',
    description: 'आदरणीय सदस्यों, नमस्कार, आज का हमारा यह केस श्री चेतन अरोड़ा (9417950886)जी द्वारा दिया गया है। 40 वर्षीय असन मसीह पुत्र श्री साधक मसीह करमपुरा, नवी आबादी, गली नंबर 5, अमृतसर के वासनिक है। उनके पास मोबाइल नंबर, आधार कार्ड और कोई भी ऐडएंट्री प्रूफ नहीं है। असन मसीह रिक्शा चलाते थे। असन मसीह की एक टांग में जख्म था जिसका इलाज ना होने के कारण वह बहुत ज्यादा बढ़ गया है। गुरु नानक हॉस्पिटल में उन्होंने इलाज करवाया अब नौबत यहां तक आ गई है कि डॉक्टर्स कह रहे हैं उनकी टांग शायद काटनी पड़े। असन मसीह की पत्नी उनको छोड़कर चली गई है।उनके दो भाई भी उसकी ज्यादा मदद नहीं कर पा रहे। उनकी अपनी एक बेटी असन मसीह के दोनों भाइयों के पास रहती है। असन मसीह की टांग बहुत ज्यादा गल चुकी है हमारे एक सदस्य रविंदर जी(9988423440,,, 987788773) उनका इलाज और उनकी हेल्प कर रहे हैं। रविंदर जी ने प्रीत हॉस्पिटल, रतन सिंह रोड, नवी आबादी, फतेहगढ़ चूड़ियां रोड, अमृतसर से डॉक्टर जे एस ग्रोवर से ट्रीटमेंट करवा रहे हैं, जिसके चलते रविंदर जी लेट्स हेल्प से असन मसीह के लिए मदद चाहते हैं। डॉक्टर ने आश्वासन दिया है अगर एक ऑपरेशन हो जाए तो शायद वह टांग बच सकती है। रविंदर जी कि सोच है कि अगर उनकी टांग बच जाए तो वह फिर से रिक्शा चलाकर अपना जीवन व्यतीत कर सकेंगे। इस दिक्कतों के चलते उनकी पत्नी उन्हें छोड़ कर चली गई है और कोई भी रिलेटिव उनकी मदद नहीं कर पा रहा। असन मसीह को नशे की आदत थी लेकिन पिछले चार-पांच महीनों से रविंद्र जी के कहने पर उन्होंने नशा छोड़ दिया है। असन मसीह के इलाज में रविंदर जी के साथ हमारी एक अन्य सदस्य रुपाली जी(7508720852) भी उनकी मदद कर रहे हैं। असहन मशीन के ऑपरेशन के लिए हमारे यह मेंबर लेट्स हेल्प से कुछ दवाइयों, टेस्टों,और हॉस्पिटल के खर्चो के लिए कुछ आर्थिक मदद चाहते हैं, कृपा हमारा मार्गदर्शन कीजिए और हमें सहायता का हाथ बढ़ाने की अनुमति दीजिए धन्यवाद',
    gender: 'm',
    age: 40,
    address: 'करमपुरा, नवी आबादी, गली नंबर 5, अमृतसर',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '8427384973',
    referredOn: '09/10/2019',
    approvedOn: '09/10/2019',
    title: 'No Title',
    caseType: 'ration',
    name: 'Gyan Singh (C/o Babita)',
    contactRelation: 'self',
    contactPerson: 'Gyan Singh (C/o Babita)',
    description: 'आदरणीय सदस्यों, आज का हमारा यह केस बबीता 8427384973 पत्नी नरेंद्र कुमार जी द्वारा दिया गया है। ज्ञान सिंह पुत्र सरदार करतार सिंह, बड़ागांव, डिस्ट्रिक्ट शाहजहांपुर\' यूपी\' नियर पलिया के रहने वाले हैं। जिनकी पत्नी का 8 साल पहले देहांत हो चुका है। वह अमृतसर में दरबार स���हब के आसपास रहते हैं। सेवा करते हैं और यही गोल्डन टेंपल के बाहर सो जाते हैं। उनका कोई भी बच्चा उनके साथ नहीं रहता। शनि मंदिर,चौक घंटाघर के पास जो छबील है, उसमें वह सेवा करते हैं। पिछले बरस एक टेंपो के साथ एक्सीडेंट हो जाने से उनकी टांग में जख्म हो गया था। जिसका इलाज ना करा पाने के कारण ज्ञान जी का जख्म बढ़ता चला गया और अब ज्यादा दिक्कत दे रहा है। बबीता वाइफ ऑफ नरेंद्र सिंह, प्रताप एवेन्यू, हाउस नंबर209, ऑपोजिट मॉल आफ अमृतसर, अमृतसर। यह बबीता नामक स्त्री जो कि उस छबील में सेवा करती है उन्होंने ज्ञान सिंह की सेवा ली हुई है और वह उनका इलाज करवा रहे हैं छबील से भी संगत ने उनका इलाज कराने में मदद की है। बबीता जी लेट्स हेल्प से ज्ञान सिंह के लिए कुछ मदद चाहते हैं। ज्ञान सिंह इस समय बीबी कोला हॉस्पिटल, 100 फोटी रोड, वार्ड B बेड नंबर 14 में दाखिल है। उनके इलाज में अभी तक 30 से 35000 लग चुका है बबीता जी और ज्ञान सिंह जी लेट्स हेल्प से उनके इलाज के लिए कुछ मदद चाहते हैं कृपा हमें हमारा मार्गदर्शन कीजिए। धन्यवाद',
    gender: 'm',
    address: ' बड़ागांव, डिस्ट्रिक्ट शाहजहांपुर\' यूपी\' नियर पलिया',
    city: 'Palia',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '7087824147',
    referredOn: '09/04/2019',
    approvedOn: '09/04/2019',
    title: 'spent for medicine and hospital charges for Mr. Vikrant.(7087824147) Case referred by Mr. Navneet Choudhary 98724-24347',
    caseType: 'ration',
    name: 'Vikrant Kumar',
    contactRelation: 'self',
    contactPerson: 'Vikrant Kumar',
    description: 'आदरणीय सदस्यों, नमस्कार आज का हमारा यह केस श्री नवनीत चौधरी (9872424347.7986898931)जी द्वारा दिया गया है। विक्रांत कुमार नामक व्यक्ति जिसकी उम्र 38 साल है, दुलो वाला कटरा, सिकंदर वाली गली, इनसाइड लोहगढ़ गेट, अमृतसर का निवासी है। Mobile no. 7087824147 उपरोक्त व्यक्ति को फेफड़ों की प्रॉब्लम है, इस समय वह संजीवनी हॉस्पिटल, इनसाइड लोहागढ़ गेट, डॉ अजय गुप्ता के हॉस्पिटल में दाखिल है। डॉक्टर कहते हैं कि उनके फेफड़ों में बहुत ज्यादा इंफेक्शन है जिसके चलते वह पहले भी रतन सिंह चौक में किसी हॉस्पिटल में एडमिट थे, विक्रांत कुमार जी shawl की कढ़ाई का काम करते हैं जो कि हर महीने 6 से 7000 तक कमा पाते हैं उनकी पत्नी किसी दवाइयों की दुकान पर लगी हुई है, जो कि ₹3000 प्रति महीना कमा पाती है। उनके दो बच्चे स्कूलों में पढ़ते हैं। उनका अपना घर है और जॉइंट फैमिली में रहते हैं उनके एक भाई को लकवा मार गया है, वह भी उसी घर में रहता है, विक्रम जी के फादर मदर नहीं है। विक्रम जी हॉस्पिटल में ऑलरेडी 20 से 25000 तक लगा चुके हैं जोकि कुछ मित्रों और रिश्तेदारों ने मदद की है, लेकिन वह अभी बी दाखिल है इस दिक्कत के चलते उन्हें लेट्स हेल्प से कुछ मदद की जरूरत है कृपा हमें ऐसे करने की इजाजत दीजिए। धन्यवाद',
    gender: 'm',
    age: 38,
    address: ' दुलो वाला कटरा, सिकंदर वाली गली, इनसाइड लोहगढ़ गेट, अमृतसर',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '6283901525',
    referredOn: '09/30/2019',
    approvedOn: '09/30/2019',
    title: 'No Title',
    caseType: 'ration',
    name: 'Naajdeep Kaur',
    contactRelation: 'self',
    contactPerson: 'Naajdeep Kaur',
    description: 'आदरणीय सदस्यों, नमस्कार हमारा आज का यह केस किसी अज्ञात नंबर से कॉल आया था और नंबर यह था (97807 53520) नाजदीप कौर उम्र 14 साल सुपुत्री गुरजंट सिंह पुत्र सरदार बुआ सिंह, गांव सेंसरा, नजदीक गुरु का बाग, नियर कुकड़ा वाला, तहसील अजनाला, डिस्ट्रिक अमृतसर। मोबाइल नंबर (6283901525)के वासी है। नाजदीप को बचपन से ही इम्यून सिस्टम की एक सीरियस प्रॉब्लम है। जिसके कारण उसे हर महीने कुछ इंजेक्शन लगते हैं। उसका इलाज पीजीआई से चलता है। पिछले 4 सालों से उसे 24000 के इंजेक्शन हर महीने लगते हैं, जे इंजेक्शन पीजीआई की एक सुखमणि सोसाइटी द्वारा 3 साल तक उन्हें दिए गए लेकिन अब यह सुखमणि सोसाइटी यह इंजेक्शन उन्हें नहीं दे पा रही, नाजदीप के पिताजी का खेतीबाड़ी का काम है। उनकी जमीन इतनी ज्यादा नहीं है कि वह इन इंजेक्शनओं का खर्चा उठा सकते। गुरजंट सिंह के 3 पुत्र जोकि इसी बीमारी से ग्रसित थे 8-9 महीने जीकर, तीनो के तीनो की मृत्यु हो गई है। यह लड़की नाजदीप आठवीं कक्षा में पढ़ती है उसे हर महीने 24000 के इंजेक्शनओं की जरूरत है हर महीने 4 इंजेक्शन लगते हैं गुरजंट जी लेट्स हेल्प से 2 इंजेक्शन प्रति महीना कुछ महीनों के लिए चाहते हैं। आप सभी से अनुरोध है कृपा इस सब को मद्देनजर रखते हुए हमारा मार्गदर्शन कीजिए धन्यवाद',
    gender: 'f',
    age: 14,
    address: ' गांव सेंसरा, नजदीक गुरु का बाग, नियर कुकड़ा वाला, तहसील अजनाला, डिस्ट्रिक अमृतसर',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}, {
    contactNo: '9779365221',
    referredOn: '12/26/2019',
    approvedOn: '12/26/2019',
    title: 'spent for the ration of Ms. Pooja Arora',
    caseType: 'ration',
    name: 'Pooja Arora',
    contactRelation: 'self',
    contactPerson: 'Pooja Arora',
    gender: 'f',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
}];

const mockCasesData = new Array(200).join(',').split(',');

let initiated = 0, added = 0, notAdded = 0, vikram, gurinder;

const addCase = ($case, callback) => {

    // For Mock Data
    // START
    $case = {};
    $case.contactNo = phoneNo();
    $case.referredOn = $case.approvedOn = recentDate();
    $case.description = randomWords(10, 60);
    $case.title = randomWords(3, 8);
    $case.caseType = randomItem(caseTypes);
    $case.name = pName();
    $case.contactRelation = randomItem(relationTypes);
    $case.contactPerson = pName();
    $case.gender = gender();
    $case.country = country();
    $case.state = state();
    $case.city = city();
    //   END

    $case.showContactNos = bool();
    $case.showAddress = bool();
    $case.vAuthUser = vikram;
    $case.isApproved = true;
    $case.approvedOn = new Date($case.approvedOn);
    $case.referredOn = new Date($case.referredOn);
    $case.upVoters = [vikram, gurinder];

    initiated++;
    CaseModel.saveCase(Object.assign(new CaseModel(), $case)).then(
        saveRes => {
            added++;
            if (initiated === added + notAdded) {
                console.log('Cases: %d added , %d failed to add', added, notAdded);
            }
            callback instanceof Function && callback();
        },
        saveErr => {
            notAdded++;
            if (initiated === added + notAdded) {
                console.log('Cases: %d added , %d failed to add', added, notAdded);
            }
        })
        .catch(saveReason => {
            notAdded++;
            if (initiated === added + notAdded) {
                console.log('Cases: %d added , %d failed to add', added, notAdded);
            }
        });
};

(async () => {
    vikram = (await UserModel.findOne({ email: 'vikram1vicky@gmail.com' }).select('userId -_id').exec()).userId;
    gurinder = (await UserModel.findOne({ email: 'gurinder1god@gmail.com' }).select('userId -_id').exec()).userId;
    mockCasesData.map(addCase);
})();

// CaseModel.insertMany(mockCasesData, (err, docs) => {
//     if (err) {
//         console.error('CaseModel.insertMany: Failed', err);
//         return false;
//     }
//     console.log('%d Cases added successfully!!!', docs.length);
// });